### ISSUE TITLE
Exception at reading data from websocket subscription

### ISSUE THREAD

**Issue by Lu05** [JKorf/Bybit.Net#10]
I tried to subscribe to UsdPerpetualStreams.SubscribeToOrderUpdatesAsync and UsdPerpetualStreams.SubscribeToPositionUpdatesAsync via websockets. There is no response bit an exception is logged.
To test this simply subscribe and place an order. This is on testnet but I don't think there is a big difference.

Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
2022.01.25 11:32:34:718 | Error | Bybit      | Deserialize JsonReaderException: Unexpected character encountered while parsing number: T. Path '', line 1, position 10. Path: , LineNumber: 1, LinePosition: 10, data: [
  {
    "order_id": "19bffe79-de68-4c53-9515-4f91b0c70112",
    "order_link_id": "",
    "symbol": "BTCUSDT",
    "side": "Buy",
    "order_type": "Market",
    "price": 38262,
    "qty": 0.01,
    "leaves_qty": 0,
    "last_exec_price": 36442,
    "cum_exec_qty": 0.01,
    "cum_exec_value": 364.411,
    "cum_exec_fee": 0.0273315,
    "time_in_force": "ImmediateOrCancel",
    "create_type": "CreateByUser",
    "cancel_type": "UNKNOWN",
    "order_status": "Filled",
    "take_profit": 0,
    "stop_loss": 0,
    "trailing_stop": 0,
    "create_time": "2022-01-25T10:32:34.519268798Z",
    "update_time": "2022-01-25T10:32:34.519369Z",
    "reduce_only": false,
    "close_on_trigger": false,
    "position_idx": "1"
  }
]
2022.01.25 11:32:34:725 | Warning | Bybit      | Failed to deserialize BybitOrderUpdate object: : Deserialize JsonReaderException: Unexpected character encountered while parsing number: T. Path '', line 1, position 10. Path: , LineNumber: 1, LinePosition: 10, data: [
  {
    "order_id": "19bffe79-de68-4c53-9515-4f91b0c70112",
    "order_link_id": "",
    "symbol": "BTCUSDT",
    "side": "Buy",
    "order_type": "Market",
    "price": 38262,
    "qty": 0.01,
    "leaves_qty": 0,
    "last_exec_price": 36442,
    "cum_exec_qty": 0.01,
    "cum_exec_value": 364.411,
    "cum_exec_fee": 0.0273315,
    "time_in_force": "ImmediateOrCancel",
    "create_type": "CreateByUser",
    "cancel_type": "UNKNOWN",
    "order_status": "Filled",
    "take_profit": 0,
    "stop_loss": 0,
    "trailing_stop": 0,
    "create_time": "2022-01-25T10:32:34.519268798Z",
    "update_time": "2022-01-25T10:32:34.519369Z",
    "reduce_only": false,
    "close_on_trigger": false,
    "position_idx": "1"
  }
] [
  {
    "order_id": "19bffe79-de68-4c53-9515-4f91b0c70112",
    "order_link_id": "",
    "symbol": "BTCUSDT",
    "side": "Buy",
    "order_type": "Market",
    "price": 38262,
    "qty": 0.01,
    "leaves_qty": 0,
    "last_exec_price": 36442,
    "cum_exec_qty": 0.01,
    "cum_exec_value": 364.411,
    "cum_exec_fee": 0.0273315,
    "time_in_force": "ImmediateOrCancel",
    "create_type": "CreateByUser",
    "cancel_type": "UNKNOWN",
    "order_status": "Filled",
    "take_profit": 0,
    "stop_loss": 0,
    "trailing_stop": 0,
    "create_time": "2022-01-25T10:32:34.519268798Z",
    "update_time": "2022-01-25T10:32:34.519369Z",
    "reduce_only": false,
    "close_on_trigger": false,
    "position_idx": "1"
  }
]
Exception thrown: 'System.ArgumentOutOfRangeException' in System.Private.CoreLib.dll
'ConsoleApp1.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.1\System.Diagnostics.StackTrace.dll'. 
'ConsoleApp1.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.1\System.Reflection.Metadata.dll'. 
'ConsoleApp1.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.1\System.Collections.Immutable.dll'. 
2022.01.25 11:32:34:932 | Error | Bybit      | Socket 1 Exception during message processing
Exception: ArgumentOutOfRangeException - Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bybit.Net.Clients.BybitSocketClient.MessageMatchesHandler(SocketConnection socketConnection, JToken message, Object request)
   at CryptoExchange.Net.Sockets.SocketConnection.HandleData(MessageEvent messageEvent)

Data: {
  "topic": "order",
  "action": "",
  "data": [
    {
      "order_id": "19bffe79-de68-4c53-9515-4f91b0c70112",
      "order_link_id": "",
      "symbol": "BTCUSDT",
      "side": "Buy",
      "order_type": "Market",
      "price": 38262,
      "qty": 0.01,
      "leaves_qty": 0,
      "last_exec_price": 36442,
      "cum_exec_qty": 0.01,
      "cum_exec_value": 364.411,
      "cum_exec_fee": 0.0273315,
      "time_in_force": "ImmediateOrCancel",
      "create_type": "CreateByUser",
      "cancel_type": "UNKNOWN",
      "order_status": "Filled",
      "take_profit": 0,
      "stop_loss": 0,
      "trailing_stop": 0,
      "create_time": "2022-01-25T10:32:34.519268798Z",
      "update_time": "2022-01-25T10:32:34.519369Z",
      "reduce_only": false,
      "close_on_trigger": false,
      "position_idx": "1"
    }
  ]
}
Exception thrown: 'System.ArgumentOutOfRangeException' in System.Private.CoreLib.dll
2022.01.25 11:32:34:960 | Error | Bybit      | Socket 1 Exception during message processing
Exception: ArgumentOutOfRangeException - Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bybit.Net.Clients.BybitSocketClient.MessageMatchesHandler(SocketConnection socketConnection, JToken message, Object request)
   at CryptoExchange.Net.Sockets.SocketConnection.HandleData(MessageEvent messageEvent)

Data: {
  "topic": "position",
  "action": "update",
  "data": [
    {
      "user_id": "443745",
      "symbol": "BTCUSDT",
      "size": 0.01,
      "side": "Buy",
      "position_value": 364.411,
      "entry_price": 36441.098,
      "liq_price": 32979.5,
      "bust_price": 32797,
      "leverage": 10,
      "order_margin": 0,
      "position_margin": 36.68708,
      "occ_closing_fee": 0.2459775,
      "take_profit": 0,
      "tp_trigger_by": "UNKNOWN",
      "stop_loss": 0,
      "sl_trigger_by": "UNKNOWN",
      "trailing_stop": 0,
      "realised_pnl": -3.9626534,
      "auto_add_margin": "0",
      "cum_realised_pnl": -4.0535393,
      "position_status": "Normal",
      "position_id": "0",
      "position_seq": "10383",
      "adl_rank_indicator": "2",
      "free_qty": 0.01,
      "tp_sl_mode": "Full",
      "risk_id": "1",
      "isolated": true,
      "mode": "BothSide",
      "position_idx": "1"
    },
    {
      "user_id": "443745",
      "symbol": "BTCUSDT",
      "size": 0,
      "side": "Sell",
      "position_value": 0,
      "entry_price": 0,
      "liq_price": 0,
      "bust_price": 0,
      "leverage": 10,
      "order_margin": 0,
      "position_margin": 0,
      "occ_closing_fee": 0,
      "take_profit": 0,
      "tp_trigger_by": "UNKNOWN",
      "stop_loss": 0,
      "sl_trigger_by": "UNKNOWN",
      "trailing_stop": 0,
      "realised_pnl": -0.9992362,
      "auto_add_margin": "0",
      "cum_realised_pnl": -0.9992362,
      "position_status": "Normal",
      "position_id": "0",
      "position_seq": "10380",
      "adl_rank_indicator": "0",
      "free_qty": 0,
      "tp_sl_mode": "Full",
      "risk_id": "1",
      "isolated": true,
      "mode": "BothSide",
      "position_idx": "2"
    }
  ]
}

**Comment by JKorf** [comment]
Hi, thanks for the report. This should be fixed in beta5 which should be available in a few minutes.

**Comment by Lu05** [comment]
@JKorf 
thanks for looking into that so fast.
The behavior changed with beta5.
I receive order events but no position events.
Also some exceptions are still logged at the output window.

Exception thrown: 'System.ArgumentOutOfRangeException' in System.Private.CoreLib.dll
2022.01.25 19:34:47:317 | Error | Bybit      | Socket 1 Exception during message processing
Exception: ArgumentOutOfRangeException - Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bybit.Net.Clients.BybitSocketClient.MessageMatchesHandler(SocketConnection socketConnection, JToken message, Object request)
   at CryptoExchange.Net.Sockets.SocketConnection.HandleData(MessageEvent messageEvent)

Data: {
  "topic": "order",
  "action": "",
  "data": [
    {
      "order_id": "843ddc3d-2067-429f-83b8-71a358f57658",
      "order_link_id": "",
      "symbol": "BNBUSDT",
      "side": "Buy",
      "order_type": "Market",
      "price": 401.25,
      "qty": 1,
      "leaves_qty": 0,
      "last_exec_price": 382.45,
      "cum_exec_qty": 1,
      "cum_exec_value": 382.44998,
      "cum_exec_fee": 0.2868375,
      "time_in_force": "ImmediateOrCancel",
      "create_type": "CreateByClosing",
      "cancel_type": "UNKNOWN",
      "order_status": "Filled",
      "take_profit": 0,
      "stop_loss": 0,
      "trailing_stop": 0,
      "create_time": "2022-01-25T18:34:41.628161664Z",
      "update_time": "2022-01-25T18:34:41.628235Z",
      "reduce_only": true,
      "close_on_trigger": true,
      "position_idx": "2"
    }
  ]
}
Exception thrown: 'System.ArgumentOutOfRangeException' in System.Private.CoreLib.dll
2022.01.25 19:34:47:350 | Error | Bybit      | Socket 1 Exception during message processing
Exception: ArgumentOutOfRangeException - Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bybit.Net.Clients.BybitSocketClient.MessageMatchesHandler(SocketConnection socketConnection, JToken message, Object request)
   at CryptoExchange.Net.Sockets.SocketConnection.HandleData(MessageEvent messageEvent)

Data: {
  "topic": "position",
  "action": "update",
  "data": [
    {
      "user_id": "443745",
      "symbol": "BNBUSDT",
      "size": 0,
      "side": "Sell",
      "position_value": 0,
      "entry_price": 0,
      "liq_price": 0,
      "bust_price": 0,
      "leverage": 10,
      "order_margin": 0,
      "position_margin": 0,
      "occ_closing_fee": 0,
      "take_profit": 0,
      "tp_trigger_by": "UNKNOWN",
      "stop_loss": 0,
      "sl_trigger_by": "UNKNOWN",
      "trailing_stop": 0,
      "realised_pnl": -38.516853,
      "auto_add_margin": "0",
      "cum_realised_pnl": -67.068794,
      "position_status": "Normal",
      "position_id": "0",
      "position_seq": "10398",
      "adl_rank_indicator": "0",
      "free_qty": 0,
      "tp_sl_mode": "Full",
      "risk_id": "251",
      "isolated": false,
      "mode": "BothSide",
      "position_idx": "2"
    },
    {
      "user_id": "443745",
      "symbol": "BNBUSDT",
      "size": 0,
      "side": "Buy",
      "position_value": 0,
      "entry_price": 0,
      "liq_price": 0,
      "bust_price": 0,
      "leverage": 10,
      "order_margin": 0,
      "position_margin": 0,
      "occ_closing_fee": 0,
      "take_profit": 0,
      "tp_trigger_by": "UNKNOWN",
      "stop_loss": 0,
      "sl_trigger_by": "UNKNOWN",
      "trailing_stop": 0,
      "realised_pnl": 0,
      "auto_add_margin": "0",
      "cum_realised_pnl": 0,
      "position_status": "Normal",
      "position_id": "0",
      "position_seq": "145",
      "adl_rank_indicator": "0",
      "free_qty": 0,
      "tp_sl_mode": "Full",
      "risk_id": "251",
      "isolated": false,
      "mode": "BothSide",
      "position_idx": "1"
    }
  ]
}

**Comment by altitoo** [comment]
I have same error as described, fixed it changing code to this 
`
protected override bool MessageMatchesHandler(SocketConnection socketConnection, JToken message, object request)
        {
            if (message.Type != JTokenType.Object)
                return false;

            var topic = message["topic"]?.ToString();
            if (topic == null)
                return false;

            if (socketConnection.ApiClient.GetType() == typeof(BybitSocketClientSpotStreams))
            {
                var bRequest = ((BybitSpotRequestMessage)request);
                var requestSymbols = bRequest.Parameters["symbol"]?.ToString().Split(',');
                var symbol = message["params"]?["symbol"]?.ToString();

                if (bRequest.Operation != topic)
                    return false;

                if (!requestSymbols.Contains(symbol))
                    return false;

                var klineInterval = message["params"]?["klineType"]?.ToString();
                if (klineInterval != null && bRequest.Parameters.ContainsKey("klineType"))
                {
                    if (klineInterval != (string)bRequest.Parameters["klineType"])
                        return false;
                }

                return true;
            }
            else
            {
                var requestParams = ((BybitFuturesRequestMessage)request).Parameters;
                if (requestParams.Any(p => topic == p.ToString()))
                    return true;

                var split = topic.Split('.');
                var symbol = split.Last();
                //var mainTopic = topic.Substring(0, topic.Length - symbol.Length - 1);

                if (requestParams.Any(p => (string)p == topic))
                    return true;

                return false;
            }
        }
`

Now im having this error at deserialize the position 

{: Deserialize JsonReaderException: Could not convert string to boolean: 0. Path 'data[0].auto_add_margin', line 1, position 390. Path: data[0].auto_add_margin, LineNumber: 1, LinePosition: 390, data: [
  {
    "user_id": "XXXXXX",
    "symbol": "BTCUSDT",
    "size": 0,
    "side": "Buy",
    "position_value": 0,
    "entry_price": 0,
    "liq_price": 0,
    "bust_price": 0,
    "leverage": 25,
    "order_margin": 0,
    "position_margin": 0,
    "occ_closing_fee": 0,
    "take_profit": 0,
    "tp_trigger_by": "UNKNOWN",
    "stop_loss": 0,
    "sl_trigger_by": "UNKNOWN",
    "trailing_stop": 0,
    "realised_pnl": -0.06354503,
    "auto_add_margin": "0",
    "cum_realised_pnl": XXXX,
    "position_status": "Normal",
    "position_id": "0",
    "position_seq": "663350",
    "adl_rank_indicator": "0",
    "free_qty": 0,
    "tp_sl_mode": "Full",
    "risk_id": "1",
    "isolated": true,
    "mode": "BothSide",
    "position_idx": "1"
  }
]}

This error happens when trying to deserialize the position from bybit

**Comment by JKorf** [comment]
Seems like the server sends "0" (string value) as a boolean value, which isn't valid json but alright.. I've fixed the parsing in the latest version, let me know if you have any other issues.

**Comment by Lu05** [comment]
@JKorf  it's a bit strange.
The position updates are working now but only if I do NOT subscribe to the UserTradeUpdates.
`  await socketClient.UsdPerpetualStreams.SubscribeToPositionUpdatesAsync(PosUpdates);
   await socketClient.UsdPerpetualStreams.SubscribeToUserTradeUpdatesAsync(UserTradeHandler);`

This will execute the PosHandler but gives an exception at the UserTradeHandler.
But the UserTradeHandler is working wenn I don't subscribe to the PositionUpdates.

2022.01.30 19:41:04:210 | Error | Bybit      | Socket 1 Exception during message processing
Exception: ArgumentOutOfRangeException - Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bybit.Net.Clients.BybitSocketClient.MessageMatchesHandler(SocketConnection socketConnection, JToken message, Object request)
   at CryptoExchange.Net.Sockets.SocketConnection.HandleData(MessageEvent messageEvent)

Data: {
  "topic": "position",
  "action": "update",
  "data": [
    {
      "user_id": "443745",
      "symbol": "BNBUSDT",
      "size": 2,
      "side": "Sell",
      "position_value": 753.64996,
      "entry_price": 376.82498,
      "liq_price": 5291.35,
      "bust_price": 5295.1,
      "leverage": 10,
      "order_margin": 0,
      "position_margin": 9844.541,
      "occ_closing_fee": 7.9426503,
      "take_profit": 0,
      "tp_trigger_by": "UNKNOWN",
      "stop_loss": 0,
      "sl_trigger_by": "UNKNOWN",
      "trailing_stop": 0,
      "realised_pnl": -26.630512,
      "auto_add_margin": "0",
      "cum_realised_pnl": -95.171776,
      "position_status": "Normal",
      "position_id": "0",
      "position_seq": "30804",
      "adl_rank_indicator": "2",
      "free_qty": 2,
      "tp_sl_mode": "Full",
      "risk_id": "251",
      "isolated": false,
      "mode": "BothSide",
      "position_idx": "2"
    },
    {
      "user_id": "443745",
      "symbol": "BNBUSDT",
      "size": 0,
      "side": "Buy",
      "position_value": 0,
      "entry_price": 0,
      "liq_price": 0,
      "bust_price": 0,
      "leverage": 10,
      "order_margin": 0,
      "position_margin": 0,
      "occ_closing_fee": 0,
      "take_profit": 0,
      "tp_trigger_by": "UNKNOWN",
      "stop_loss": 0,
      "sl_trigger_by": "UNKNOWN",
      "trailing_stop": 0,
      "realised_pnl": 0,
      "auto_add_margin": "0",
      "cum_realised_pnl": 0,
      "position_status": "Normal",
      "position_id": "0",
      "position_seq": "192",
      "adl_rank_indicator": "0",
      "free_qty": 0,
      "tp_sl_mode": "Full",
      "risk_id": "251",
      "isolated": false,
      "mode": "BothSide",
      "position_idx": "1"
    }
  ]
}
Exception thrown: 'System.ArgumentOutOfRangeException' in System.Private.CoreLib.dll
2022.01.30 19:41:04:246 | Error | Bybit      | Socket 1 Exception during message processing
Exception: ArgumentOutOfRangeException - Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Bybit.Net.Clients.BybitSocketClient.MessageMatchesHandler(SocketConnection socketConnection, JToken message, Object request)
   at CryptoExchange.Net.Sockets.SocketConnection.HandleData(MessageEvent messageEvent)

Data: {
  "topic": "execution",
  "data": [
    {
      "symbol": "BNBUSDT",
      "side": "Sell",
      "order_id": "6f40533b-60cc-4f3b-a386-92e54d6355f9",
      "exec_id": "e87b05ed-e9f2-5f58-94e6-869d1c326099",
      "order_link_id": "",
      "price": 376.85,
      "order_qty": 1,
      "exec_type": "Trade",
      "exec_qty": 1,
      "exec_fee": 0.2826375,
      "leaves_qty": 0,
      "is_maker": false,
      "trade_time": "2022-01-30T18:41:02.7678Z"
    }
  ]
}

**Comment by JKorf** [comment]
Another fix done. This should be fixed in beta7.

**Comment by Lu05** [comment]
@JKorf  Yes, working now, thanks.
I will close this issue.
