### ISSUE TITLE
GetKlinesAsync returns inaccurate price

### ISSUE THREAD

**Issue by Amannda123** [JKorf/Bybit.Net#100]
Hi, its been a while... 

BybitClient.UsdPerpetualApi.ExchangeData.GetKlinesAsync seems to return only rounded numbers as price informations.
Turnover for example is way more precise. 

![grafik](https://user-images.githubusercontent.com/61044409/207834456-c009fb6f-5235-4eeb-a1a4-fe78a98c1829.png)

Shouldnt be a big issue, just wanted to mention it.

**Comment by kulikov-dev** [comment]
@Amannda123 Hello, Amanda. I believe, it's just a coincidence, because it could be the real price that the Binance send to you.. I checked in on XRPUSDT pair and got an accurate results:
![image](https://user-images.githubusercontent.com/40471760/207936978-21e0be59-b442-4259-b8e4-73d5dc0417e7.png)

**Comment by kulikov-dev** [comment]
@JKorf I think it can be closed.
