### ISSUE TITLE
SetPositionModeAsync Error

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bybit.Net#103]
Dim mert = Await clientBybit.UsdPerpetualApi.Account.SetPositionModeAsync("BTCUSDT", "USDT", True, receiveWindow:=10000)

**I got this error**: System.ArgumentNullException: 'Value cannot be null.
Parameter name: One of 'coin' or 'symbol' parameters is required!'

![Error](https://user-images.githubusercontent.com/39071426/209531569-04ab360d-ae74-4682-ad2b-08a50e943208.png)

**Comment by kulikov-dev** [comment]
@dante1989 According to the [API documentation](https://bybit-exchange.github.io/docs/futuresV2/linear/#t-switchpositionmode), in this method we can pass only ONE of these parameters, not both of them.
In your casee it should be:
`Dim mert = Await clientBybit.UsdPerpetualApi.Account.SetPositionModeAsync("BTCUSDT",  null, True, receiveWindow:=10000)`
or
`Dim mert = Await clientBybit.UsdPerpetualApi.Account.SetPositionModeAsync(null, "USDT", True, receiveWindow:=10000)`

**Comment by dante1989** [comment]
> @dante1989 According to the [API documentation](https://bybit-exchange.github.io/docs/futuresV2/linear/#t-switchpositionmode), in this method we can pass only ONE of these parameters, not both of them. In your casee it should be: `Dim mert = Await clientBybit.UsdPerpetualApi.Account.SetPositionModeAsync("BTCUSDT", null, True, receiveWindow:=10000)` or `Dim mert = Await clientBybit.UsdPerpetualApi.Account.SetPositionModeAsync(null, "USDT", True, receiveWindow:=10000)`

Thank you
