### ISSUE TITLE
Error converting IEnumerable<T> in Result.Error

### ISSUE THREAD

**Issue by nikkozp** [JKorf/Bybit.Net#104]
Request: 
`SendRequestAsync<BybitResult<T>> where T is IEnumerator`

Result:
> {"ret_code":10001,"ret_msg":"params error: invalid symbol","**result":{ }**, "ext_code":"","ext_info":"","time_now":"1673512873.165919","rate_limit_status":599,"rate_limit":600,"rate_limit_reset_ms":1673512873165}

expected **"result": [ ]**

Error: 
> [18] Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1

The error itself occurs in the library CryptoExchange.Net . When instead of the expected list, json returns the type as an object, during an error

**Comment by kulikov-dev** [comment]
@nikkozp Can you attach the code, that produced this error?

**Comment by nikkozp** [comment]
You can execute any query whose response is IEnumerable

**Comment by kulikov-dev** [comment]
@nikkozp Turn on LogTracing:
`  client.ClientOptions.LogLevel = LogLevel.Trace;`
And check the Data field in the Error property. Looks like you have a problem with your API key or passed symbol.

**Comment by kulikov-dev** [comment]
@nikkozp Can you send information from the Data field that I described in the previous message?

**Comment by nikkozp** [comment]
@kulikov-dev 

> 2023.01.17 13:14:28:849 | Error | Bybit      | [19] Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Bybit.Net.Objects.Models.BybitUsdPerpetualOrder]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
> To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
> Path 'result', line 1, position 69. data: {
>   "ret_code": 10001,
>   "ret_msg": "params error: invalid symbol",
>   "result": {},
>   "ext_code": "",
>   "ext_info": "",
>   "time_now": "1673957668.729600",
>   "rate_limit_status": 599,
>   "rate_limit": 600,
>   "rate_limit_reset_ms": 1673957668729
> }


![image](https://user-images.githubusercontent.com/11537426/212896691-1d9ca79f-a222-45c3-85ee-bc9f4af0a20d.png)

**Comment by kulikov-dev** [comment]
@nikkozp In the OriginalData you have ret_code and ret_msg which help you to understand the problem.
In your case you passed the wrong symbol, as I said early. Message "invalid symbol" from the exchange explains it.
What symbol do you try to pass?

**Comment by nikkozp** [comment]
@kulikov-dev 

It's not that the symbol is incorrect, but that it can't convert `ret_msg` to `Error.Message`. And it turns out that in the Error class it is written `Deserialize JsonSerializationException:`

**Comment by kulikov-dev** [comment]
@nikkozp It can't convert because you passed the wrong symbol. If you call `GetOpenOrderRealTimeAsync` method - you will get the same "Invalid symbol" message. Due to CryptoExchange architecture - there isn't easy way to process such kind of exchange errors for IEnumerable methods (as the result of your query is the object). If it's a problem - please open issue in the CryptoExchange lib, as it doesn't connect directly with Bybit.

**Comment by JKorf** [comment]
There is already a way to configure the error parsing in the client libraries, but it wasn't set up correctly for Bybit. It should be parsing error correctly in the latest version now
