### ISSUE TITLE
Unified Margin Account API error

### ISSUE THREAD

**Issue by BertkeOfUtrecht** [JKorf/Bybit.Net#105]
Using package 1.4.0, below code returns Server Error 10016 for UnifiedAccount Balance query. All other APIs (spot, perpetual, contract etc. work well)
Can someone help if I do sthng wrong or if this is an issue of the library?

PS: Sorry for posting here but couldn't find any tip anywhere and first time I am trying to use this lib.

BybitClient.SetDefaultOptions(new BybitClientOptions
            {
                ApiCredentials = new ApiCredentials("KEY", "SECRET"),
                LogLevel = LogLevel.Trace
            });
            var bybitClient = new BybitClient();

var uBalance = await bybitClient.DerivativesApi.UnifiedMarginApi.Account.GetWalletBalance();

Log: 
Response received in 180ms: 2023/01/14 20:50:56:497 | Debug | Bybit      | [2] Response received in 180ms: {"retCode":10016,"retMsg":"System error. Please try again later.","result":{},"retExtInfo":{},"time":1673725857903}

**Comment by kulikov-dev** [comment]
@BertkeOfUtrecht According to the API documentation it's the problem on the Bybit server side.

**Comment by BertkeOfUtrecht** [comment]
I am now checking via Bybit support, let's see what they say, thanks.
