### ISSUE TITLE
ByBit.CopyTrading.GetOrdersAsync returns incorrect price

### ISSUE THREAD

**Issue by OxfordGrid** [JKorf/Bybit.Net#106]
Steps to reproduce:
1) create a new copy trading order
2) get the list of all open orders

Expected result:
- the returned order should have price equal to the open price

Actual behaviour:
- the returned order has a random price and ValueFilled equal to the actual order price divded by 1000

![UI](https://testbybitbucket.s3.eu-west-2.amazonaws.com/ByBit+Copy+Bug.png)
![VS](https://testbybitbucket.s3.eu-west-2.amazonaws.com/ByBit+Copy+Bug+VS.png)

**Comment by OxfordGrid** [comment]
Ok, I've got an update from the ByBit API team. Apparently the returned price is their internal limit for market orders. So it's a feature, not a bug :(

**Comment by JKorf** [comment]
Seems pretty weird, but not much I can do about that unfortunately
