### ISSUE TITLE
Error when parsing the response https://api.bybit.com/spot/v3/private/my-trades

### ISSUE THREAD

**Issue by 79231232393** [JKorf/Bybit.Net#109]
unable to parse the response of values of type bool

Error = {: [32] Deserialize JsonReaderException: Could not convert string to boolean: 0. Path 'result.list[0].isBuyer', line 1, position 272. Path: result.list[0].isBuyer, LineNumber: 1, LinePosition: 272, data: {
  "retCode": 0,
  "retMsg": "OK",
  "result": {
...

{"retCode":0,"retMsg":"OK","result":{"list":[{"symbol":"XRPUSDT","id":"1345143822662853888","orderId":"1345143822520247552","tradeId":"2260000000059395662","orderPrice":"0.4014","orderQty":"12","execFee":"0.012","feeTokenId":"XRP","creatTime":"1675089639430","isBuyer":"0","isMaker":"1","matchOrderId":"1345143813326254080","makerRebate":"0","executionTime":"1675089639443"},{"symbol":"XRPUSDT","id":"1345140813618830848","orderId":"1345140813467869440","tradeId":"2260000000059394363","orderPrice":"0.4008","orderQty":"11","execFee":"0.011","feeTokenId":"XRP","creatTime":"1675089280722","isBuyer":"0","isMaker":"1","matchOrderId":"1345140792940936960","makerRebate":"0","executionTime":"1675089280737"}]},"retExtInfo":{},"time":1675089716693}

**Comment by JKorf** [comment]
Fixed in latest version
