### ISSUE TITLE
Param validation for 'symbol' failed on the 'linear_symbol' tag

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Bybit.Net#11]
Hi,
I am using Bybit.Net version 0.0.1-beta5.

I cannot send a limit buy order or market order for BITUSD (not BITUSDT) in futures.
Error header: **Param validation for 'symbol' failed on the 'linear_symbol' tag** (Error Code: 10001)
Below I am attaching the C# code block and the outgoing statement in the HTTP request.
Can you tell me what am I missing?

Code:
`var limitOrderResult = await client.UsdPerpetualApi.Trading.PlaceOrderAsync(
                                symbol: "BITUSD",
                                side: Bybit.Net.Enums.OrderSide.Buy,
                                type: Bybit.Net.Enums.OrderType.Limit,
                                quantity: 20,
                                timeInForce: Bybit.Net.Enums.TimeInForce.GoodTillCanceled,
                                reduceOnly: false,
                                closeOnTrigger: false,
                                price: 1.4M).ConfigureAwait(false);`

**Request Body:**
api_key=XXXXXXXXXXX&close_on_trigger=False&order_type=Limit&price=1.4&qty=20&recvWindow=5000&reduce_only=False&side=Buy&symbol=BITUSD&time_in_force=GoodTillCancel&timestamp=1643129586158&sign=XXXXXXXXXXXXXX

**Request URL:**
https://api.bybit.com/private/linear/order/create

**Comment by JKorf** [comment]
I think you're only allowed to send `USDT` symbols on the USD Perpetual API. The GetSymbolsAsync() call is a shared endpoint for `USD Perpetual`, `Inverse Perpetual` and `InverseFutures` api's, so not every symbol can be used on every api.

**Comment by emin-karadag** [comment]
Hi @JKorf 
I was able to send a limit buy order using InversePerpetualApi instead of UsdPerpetualApi.
