### ISSUE TITLE
DerivativesApi.ContractApi.Account.SetPositionModeAsync: position_mode invalid

### ISSUE THREAD

**Issue by Arke123** [JKorf/Bybit.Net#112]
When calling the following function bybit replys with "position_mode invalid"
bybit.DerivativesApi.ContractApi.Account.SetPositionModeAsync(Bybit.Net.Enums.PositionMode.BothSideBuy, asset: "USDT");

Mode has to be 3.
https://bybit-exchange.github.io/docs/derivatives/contract/position-mode

**Comment by JKorf** [comment]
Fixed in the latest version
