### ISSUE TITLE
BybitSocketClient - SpotStreamsV3.SubscribeToUserOrdersUpdatesAsync LogLevel issue, causing memory spikes

### ISSUE THREAD

**Issue by kekewong** [JKorf/Bybit.Net#113]
Once i execute BybitSocketClient.SpotStreamsV3.SubscribeToUserOrdersUpdatesAsync method, it connect to bybit testnet successfully. But every second it increase around 50-100MB in my backend .exe program. RAM keeps increasing until the program uses 10GB+ of RAM. After the Spot V3 stream was connected, even though the program did not received any response from web socket, but CPU is consistantly using 5-10% every second, with 50-100MB increased every second. 

I found a temporarily workaround on the memory issue. If i set the LogLevel to "LogLevel.Trace" under BybitSocketClientOptions class, the memory issue is gone and my program now consistantly using 100+MB instead of 10GB+. 
I even tried setting to LogLevel = LogLevel.None, the memory issue still persist and it seems like the only way is to set to "LogLevel.Trace"

Please refer below for my temporarily workaround: 

`BybitSocketClient BybitSocketClient = new BybitSocketClient
            (
                new BybitSocketClientOptions
                {
                    LogLevel = LogLevel.Trace,
                    ApiCredentials = new ApiCredentials(apiKey, secretKey),
                    SpotStreamsV3Options = new BybitSocketApiClientOptions
                    {
                        BaseAddress =  BybitApiAddresses.Default.SpotPrivateSocketV3ClientAddress,
                        BaseAddressAuthenticated = BybitApiAddresses.Default.SpotPrivateSocketV3ClientAddress,
                    } 
                }
            );`  

Can you please look into this issue?

Below are my setup:
1. C# .NET 6.0
2. ByBit.NET version 1.5.1 build

Thanks.

**Comment by JKorf** [comment]
That doesn't really make sense. Can you create a minimal repo demonstrating the issue?
