### ISSUE TITLE
Spot API v3 -> Get Account Balances

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Bybit.Net#114]
Hello,
Version: I am using v1.5.1. While I can get user balances with Spot API v1, I can't with Spot API v3, it comes up empty.

**Working Code:**
`var balancesResult = await bybitClient.SpotApiV1.Account.GetBalancesAsync(ct: ct);`

**Notworking Code:** 
`var balancesResult = await bybitClient.SpotApiV3.Account.GetBalancesAsync(ct: ct);`

**Comment by JKorf** [comment]
Fixed in the latest version
