### ISSUE TITLE
API V5

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bybit.Net#115]
Open API V5 brings uniformity and efficiency to Bybit's product lines, unifying Spot, Derivatives, and Options in one set of specifications.
Do you have plan to Add API V5?
https://bybit-exchange.github.io/docs/v5/upgrade-guide

**Comment by JKorf** [comment]
V5 API has been implemented and released in version 2.0.0 :)
You can access it via the `V5Api ` on the client. Please let me know if you have any issues

**Comment by dante1989** [comment]
I will feed back you soon
