### ISSUE TITLE
Spot Conditional Order

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Bybit.Net#119]
Hello,
I want to issue a conditional BUY/SELL order using API. However, no matter what parameters I gave, I was not successful. Can you show an example of a conditional order?
Thanks.

**Comment by alexander-lanin** [comment]
+1
Any way to create Spot Conditional Order?

**Comment by JKorf** [comment]
The new V5 API which is now available in version 2.0.0 should support this!

**Comment by alexander-lanin** [comment]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/68636413/232152388-22a11981-ab31-4863-9bdf-0f419f72c6f6.png)

**Comment by JKorf** [comment]
Ah my bad. Although the infrastructure is there in V5 it might not be supported
