### ISSUE TITLE
bybitClient.V5Api.Trading.GetOrdersAsync() cannot query orders with settleAsset only

### ISSUE THREAD

**Issue by Timmen** [JKorf/Bybit.Net#136]
Hello. 

With latest changes I cannot query all orders by providing settle asset like _bybitClient.V5Api.Trading.GetOrdersAsync(Category.Linear, settleAsset: "USDT"). 

Error is  "One of orderId or clientOrderId should be provided".

Do we need order id validation at all?

**Comment by JKorf** [comment]
Hi, this was accidentally introduced when fixing some other issue. Unfortunately I'm currently on holiday so I won't be able to fix it for +-1.5 weeks. If you need that functionality you could use the previous version of the library
