### ISSUE TITLE
Getting Coin-M price information with WebSocket

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Bybit.Net#138]
Hello,
I am using Bybit.Net v2.0.4.

I want to get Bybit Coin-M price information using WebSocket. When I write a code like below, websocket does not respond.
Am I using it wrong?
How do you think I can get Coin-M instant ticker information?
Thanks.

**Example:**

```
await _socketClient.V5LinearStreams.SubscribeToTickerUpdatesAsync("BTCUSD", tickerUpdate =>
{
    if (tickerUpdate != null)
    {

    }
}, stoppingToken);
```

**Comment by JKorf** [comment]
BTCUSD is not a valid symbol, try BTCUSDT
