### ISSUE TITLE
client endpoint mixup

### ISSUE THREAD

**Issue by ToSa27** [JKorf/Bybit.Net#14]
some (not all) calls under the UsdPerpetual client seem to redirect to the corresponding InversePerpetual client routines which is fine as they have the same signature but it silently uses the InversePerpetual client options as well. In my case I had only the UsdPerpetual client options configured (for testnet) and was surprised that the calls targeted the live URLs as these are the default for the InversePerpetual client... then obviously complaining about a bad API key as testnet and live are using separate keys.

**Comment by JKorf** [comment]
You're right, I didn't think of this. Should be fixed in the latest release

**Comment by ToSa27** [comment]
working fine now
