### ISSUE TITLE
json parse error

### ISSUE THREAD

**Issue by zcjack** [JKorf/Bybit.Net#145]
1.  class BybitAssetBalance
        public decimal WalletBalance { get; set; }
should change to:
        public decimal? WalletBalance { get; set; }

2.  class BybitPosition
        public decimal PositionValue { get; set; }
        public decimal MarkPrice { get; set; }
        public decimal LiquidationPrice { get; set; }
should change to:
        public decimal? PositionValue { get; set; }
        public decimal? MarkPrice { get; set; }
        public decimal? LiquidationPrice { get; set; }

![image](https://github.com/JKorf/Bybit.Net/assets/35440775/31d5eb41-b5d8-4d56-818c-49abf0040adc)

**Comment by zcjack** [comment]
3. class  BybitSpotSymbol
          public MarginTrading MarginTading { get; set; }
   should change to:
          public MarginTrading MarginTrading { get; set; }

**Comment by JKorf** [comment]
These adjustments have been implemented some time ago.
(except for the MarginTrading change, which I assume you suggest should be nullable but it doesn't seem to be null ever)
