### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by mgamache** [JKorf/Bybit.Net#146]
I was unable to get the proxy working via the BybitRestClient Options. 

 I was able to get it working by specifying a custom httpClient and associating the proxy with that. 
 
 `var bybitClient = new BybitRestClient(options => options.Proxy = new ApiProxy("http://x.x.x.x",8888) );`

**Comment by JKorf** [comment]
There was some issue with the options with earlier versions. It should be working correctly now. Let me know if this issue still exists in the latest version
