### ISSUE TITLE
"SubscribeToPositionUpdatesAsync" -> AveragePrice Error!

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Bybit.Net#150]
Hello,
I am using Bybit.Net v3.0.1.

I am running the following code block to read instant price information over Websocket.

```
await _socketClient.V5PrivateApi.SubscribeToPositionUpdatesAsync(uptade =>
{
    if (uptade is not null)
    {
        foreach (var position in uptade.Data)
        {
            var avgPrice = position.AveragePrice;
        }
    }
}, stoppingToken);
```

In the code block above, "position" displays a lot of information about my position, while "**AveragePrice**" information is 0 (zero).

Thank you.

**Comment by JKorf** [comment]
Should have been fixed in the latest version. Can you check?
