### ISSUE TITLE
V5 Api: EditOrderAsync mistake

### ISSUE THREAD

**Issue by sergixc** [JKorf/Bybit.Net#152]
_public async Task<WebCallResult<BybitOrderId>> EditOrderAsync (Category category, string symbol, string? orderId = null, string? clientOrderId = null, decimal? quantity = null, decimal? price = null, decimal? triggerPrice = null, TriggerType? triggerBy = null, decimal? orderIv = null, decimal? takeProfit = null, decimal? stopLoss = null, TriggerType? takeProfitTriggerBy = null, TriggerType? stopLossTriggerBy = null, CancellationToken ct = default(CancellationToken))
{
	if (orderId == null != (clientOrderId == null)) {
		throw new ArgumentException ("One of orderId or clientOrderId should be provided");
	}_

checking for orderId and clientOrderId throws exception if only one of two provided

**Comment by JKorf** [comment]
Fixed in latest verion
