### ISSUE TITLE
Error when buying on spot

### ISSUE THREAD

**Issue by Ctorab** [JKorf/Bybit.Net#157]
`
            var bybitClient = new BybitRestClient(options =>
            {
                options.ApiCredentials = new ApiCredentials("XXXX", "XXXX");
                /*options.InverseFuturesOptions.ApiCredentials = new ApiCredentials("FUTURES-API-KEY", "FUTURES-API-SECRET");*/
                options.RequestTimeout = TimeSpan.FromSeconds(60);
                options.AutoTimestamp = true;
            });

            var accountData = await bybitClient.SpotApiV3.Account.GetBalancesAsync();
            var orderData = await bybitClient.SpotApiV3.Trading.PlaceOrderAsync("PLANETUSDT", OrderSide.Buy, OrderType.Market, 1m, timeInForce: TimeInForce.GoodTillCanceled);
`

Hello, this is the code I'm using, when I get account balance It returns the account balance without any error, but when I try to buy on spot I can't it says {10005: Invalid API-key, IP, or permissions for action. }. API-Key is 100% valid, any IP can access the api and all premissions are active.

**Comment by JKorf** [comment]
Cleaning up old issues, I'm assuming this has since been resolved.
