### ISSUE TITLE
Missing fields in GetPositionsAsync

### ISSUE THREAD

**Issue by hcanak** [JKorf/Bybit.Net#158]
Hello,

In the following endpoint **autoAddMargin** and **positionBalance** field are missing. Can you have a look till next update?

https://bybit-exchange.github.io/docs/v5/position
 

A recommendation; I see that all fields in  **BybitPosition** class are read/write. I think it would be more appropriate when fields are init only (read only) in a **record** type. 

public record BybitPosition
{
          public bool autoAddMargin{ get; init; }
  .
  .
  .
}

**Comment by JKorf** [comment]
Fixed in the latest version. Thanks for the suggestion, makes sense. I'll look into it
