### ISSUE TITLE
V5Api.Trading.GetOrdersAsync

### ISSUE THREAD

**Issue by TuaMeta** [JKorf/Bybit.Net#163]
to create an order returns an orderid: 89c41f93-72d1-4b11-91a9-fab9243c259c, then try to retrieve the order ( V5Api.Trading.GetOrdersAsync ) and returns order does not exist

**Comment by JKorf** [comment]
Cleaning up old issues. Assuming this is working correctly, if not feel free to comment/provide some more context.
