### ISSUE TITLE
Bybit disables outdated API versions

### ISSUE THREAD

**Issue by Lexans** [JKorf/Bybit.Net#166]
Bybit disables outdated API versions. More details at the link
https://announcements.bybit.com/en-US/article/bybit-openapi-services-transition-from-legacy-version-to-new-v5-api-blt25b43a5738c00765/?utm_campaign=website&utm_source=sendgrid.com&utm_medium=email
Will this make some library functions unavailable (not v5)?

**Comment by JKorf** [comment]
Yes, the older endpoints will not work anymore. If you use V3/V5 endpoints you're all good
