### ISSUE TITLE
How can use it in testnet? thx

### ISSUE THREAD

**Issue by Nuvolari2020** [JKorf/Bybit.Net#17]
Hi, I would like to point to Testnet.. how can I do it?
like in Binance.Net I can use -> BinanceClient.SetDefaultOptions(new BinanceClientOptions(BinanceApiAddresses.TestNet ) . Thanks!

**Comment by ToSa27** [comment]
The testnet endpoints are not maintained in code (yet?) but you can set the BaseAddress in the options manually. Here is what I use but please confirm in the Bybit API docs:

For the REST client:
`
BaseAddress = testnet ? "https://api-testnet.bybit.com" : "https://api.bybit.com"
`
For the socket client:
`
BaseAddress = testnet ? "wss://stream-testnet.bybit.com/realtime_public" : "wss://stream.bybit.com/realtime_public"
BaseAddressAuthenticated = testnet ? "wss://stream-testnet.bybit.com/realtime_private" : "wss://stream.bybit.com/realtime_private"
`

Be aware that you need a dedicated API key/secret for testnet that you would need to set in the options as well.

**Comment by Nuvolari2020** [comment]
Great Thanks @ToSa27 for the help!
