### ISSUE TITLE
Missing feeType on  /v5/asset/withdraw/create

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/Bybit.Net#179]
Hi JKorf,
the method 
`        public async Task<WebCallResult<BybitId>> WithdrawAsync(...`
Does not expose the feeType parameter.

Do you plan to include it ?
Or are you interested in a PR for this ?

Thanks
Eric

**Comment by JKorf** [comment]
Hi Eric, please feel free to open a PR :)

**Comment by EricGarnier** [comment]
Done in Add feeType to withdraw V5 #180

**Comment by JKorf** [comment]
Added in latest version
