### ISSUE TITLE
InvariantCulture is missing at SetTradingStopAsync

### ISSUE THREAD

**Issue by Lu05** [JKorf/Bybit.Net#18]
Hi,

if I execute BybitClientInversePerpetualApiTrading.SetTradingStopAsync on my local machine (wich is not english culture) the call gives an error.
I think this is because CultureInfo.InvariantCulture is missing at the ToString calls for the decimal values .
So setting the price to eg 42.000 results in 42,000 which gives a 'sign!' error from bybit.

**Comment by JKorf** [comment]
You're right, thanks for the report. This has been fixed in beta10.

**Comment by Lu05** [comment]
@JKorf 
thanks for fixing that. Why is beta10 not available on nuget?

**Comment by JKorf** [comment]
It should be. It might not show up as the latest though, since the VS package manager compares the packages on string basis. Check to see if it is a little further down the list.

**Comment by Lu05** [comment]
@JKorf 
Ah, yeah, didn't see that, thanks. I is a bit confusing with the versions. beta10 didn't show as 'update' at Visual Studio. Now I updated manually to beta10 and it shows there is an update to beta9.
