### ISSUE TITLE
septa and bleeding bybit packages

### ISSUE THREAD

**Issue by pavlexander** [JKorf/Bybit.Net#189]
What are `Septa.Bybit.Net` and `Bleding.Bybit.Net` packages and how are they different from a regular `Bybit.Net` package?

If this info was present on the readme or in the package descriptions this would be nice. Currently all 3 have the same description, same project url, etc.

**Comment by JKorf** [comment]
Only Bybit.Net is made by me, the other ones are made by other developers and I don't know what their use is

**Comment by pavlexander** [comment]
I see.. thank you
