### ISSUE TITLE
V5Api.Trading.GetOrdersAsync does NOT return ExecutedFee

### ISSUE THREAD

**Issue by lasselauth** [JKorf/Bybit.Net#194]
When calling the endpoint, only "QuantityFilled" is returned, but "ExecutedFee" is not, which means that you cannot calculate the actual amount on the exchange.

Either return both "QuantityFilled" and "ExecutedFee" or extract the fee from quantity filled.

Example:
QuantityFilled: 177.43 ALT
Fee: 0.17743 ALT
ALT in Exchange: 177,25257000

Also "FeeAsset" is always null. In this example, I would expect "ALT" as the value.

**Comment by JKorf** [comment]
This is an API issue, not something I can fix unfortunately. You can try the V3 API to see if that has what you need
