### ISSUE TITLE
Instruments needs an update

### ISSUE THREAD

**Issue by brightb1ue** [JKorf/Bybit.Net#196]
https://bybit-exchange.github.io/docs/changelog/v5#rest-api

- Add response fields maxMktOrderQty
- postOnlyMaxOrderQty is useless, use maxOrderQty for Limit and PostOnly order

{"symbol":"BTCUSDT","contractType":"LinearPerpetual","status":"Trading","baseCoin":"BTC","quoteCoin":"USDT","launchTime":"1584230400000","deliveryTime":"0","deliveryFeeRate":"","priceScale":"2","leverageFilter":{"minLeverage":"1","maxLeverage":"100.00","leverageStep":"0.01"},"priceFilter":{"minPrice":"0.10","maxPrice":"199999.80","tickSize":"0.10"},"lotSizeFilter":{"maxOrderQty":"155.000","minOrderQty":"0.001","qtyStep":"0.001","postOnlyMaxOrderQty":"155.000","**maxMktOrderQty**":"100.000"},"unifiedMarginTrade":true,"fundingInterval":480,"settleCoin":"USDT","copyTrading":"both","upperFundingRate":"0.00375","lowerFundingRate":"-0.00375"}

**Comment by JKorf** [comment]
I've updated it in the latest version
