### ISSUE TITLE
PositionMode type in BybitOrderUpdate after 3.5.0 update

### ISSUE THREAD

**Issue by hcanak** [JKorf/Bybit.Net#197]
Hello,

The type of PositionMode field in BybitOrderUpdate class is Bybit.Net.Enums.V5.PositionMode in last update 3.5.0.
I think that it should be type of Bybit.Net.Enums.PositionMode. Can you check?

Bybit.Net.Enums.PositionMode  is  enum of OneWay, BothSideBuy and BothSideSell.
Bybit.Net.Enums.V5.PositionMode  is  enum of MergedSingle and BothSides.

**Comment by JKorf** [comment]
Hi, seems like you're right. I've updated the enum type and renamed it to PositionIdx in the latest version
