### ISSUE TITLE
V5Api.Trading.GetPositionsAsync cannot parse json string correctly after 3.5.0

### ISSUE THREAD

**Issue by hcanak** [JKorf/Bybit.Net#198]
Hello,

When i call V5Api.Trading.GetPositionsAsync, it gives following error;

Error Code: 
Error Message: [21] Deserialize JsonReaderException: Could not convert string to DateTime: 1708589721393. Path 'result.list[0].mmrSysUpdatedTime', line 1, position 751. Path: result.list[0].mmrSysUpdatedTime, LineNumber: 1, LinePosition: 751, data: {
  "retCode": 0,
  "retMsg": "OK",
  "result": {...

Thanks for your efford @JKorf

**Comment by JKorf** [comment]
Hi, property was missing a converter there, I've fixed it in 3.5.2
