### ISSUE TITLE
BybitOrderBookEntry.Quantity is a Decimal in Bybit.Net, and an Int in the Bybit API. What does this mean?

### ISSUE THREAD

**Issue by brspurri** [JKorf/Bybit.Net#2]
Quick question about the definition of `BybitOrderBookEntry.Quantity`...

The response for the orderbooks asks/bids `Quantity` value is of type [decimal](https://github.com/JKorf/Bybit.Net/blob/ee0f6d4a810f845ab9e329ce1f8b0a2716d836c6/ByBit.Net/Objects/Models/BybitOrderBookEntry.cs#L25) (with decimal values), but from the Bybit [documentation](https://bybit-exchange.github.io/docs/inverse/#t-websocketorderbook25), it looks like this value would be an `Int`, with much larger integer values (ie., integer number of contracts in USD).

Can someone help me understand what the definition of `BybitOrderBookEntry.Quantity` is within **Bybit.Net** is?

**Comment by JKorf** [comment]
Hi, the inverse Api's have the quantity specified in USD, while the Linear Perpetual and Spot Api's denote the value in the quote asset (for example BTC when looking at BTCUSDT).

**Comment by brspurri** [comment]
Ok, thank you for the clarification. Makes sense now.
