### ISSUE TITLE
Missing Spot API endpoint /spot/order/batch-cancel

### ISSUE THREAD

**Issue by CitrusVento** [JKorf/Bybit.Net#20]
Without this method it is impossible to cancel all active orders for the fixed symbol

**Comment by JKorf** [comment]
I've added this endpoint in the latest version

**Comment by CitrusVento** [comment]
Unfortunately method not working with LimitMaker orders without explicit indication OrderType. I think it's happens because orderTypes request parameter has a default LIMIT value. So the orderTypes parameter shouldn't actually be optional.

**Comment by JKorf** [comment]
Updated the comments for this
