### ISSUE TITLE
V5LinearApi.SubscribeToOrderbookUpdatesAsync() - Snapshot data not return

### ISSUE THREAD

**Issue by moonbugkr** [JKorf/Bybit.Net#200]
Sorry, my English is not very good

V5LinearApi.SubscribeToOrderbookUpdatesAsync() - Snapshot data not return

I noticed that the SnapshotHandler Action is missing from the above method of Orderbook.
I thought Snapshot and Delta(Update) Action were integrated.
However, I could only get Delta Data, not Snapshot Data.
Where should I get my Snapshot Data from?

Thanks.

**Comment by JKorf** [comment]
Hi, the snapshot is still available, but it has been combined in the same handler.
You can check the type like this:
```
await bybitSocketClient.V5LinearApi.SubscribeToOrderbookUpdatesAsync("BTCUSDT", data =>
{
    if (data.UpdateType == SocketUpdateType.Snapshot)
    {
        // snapshot
    }
    else
    {
        // update
    }
});
```

**Comment by moonbugkr** [comment]
I already know what it means, and it doesn't work. Only Delta Data comes in.

Thanks.

**Comment by JKorf** [comment]
I checked it and you're right. It's an easy fix, I'll push a new version later today.

The first update the server send when subscribing is the snapshot. However it already sends this before confirming the subscription, while the subscription only accepts messages once it has been confirmed.

**Comment by JKorf** [comment]
Fixed in version 3.6.1

**Comment by moonbugkr** [comment]
Thank you for the fixed version.
I've sent small donations a few times, but the BTC and ETH fees are higher than before.
Why don't you add addresses for coins like USDT as well?

**Comment by JKorf** [comment]
Yeah that was something that went through my head as well. I add some stablecoin alternative(s)
