### ISSUE TITLE
V5Api.Account.GetBalancesAsync(AccountType.Unified) throws error...

### ISSUE THREAD

**Issue by hcanak** [JKorf/Bybit.Net#202]
Hello,

V5Api.Account.GetBalancesAsync(AccountType.Unified) started to give following error;

![image](https://github.com/JKorf/Bybit.Net/assets/79494507/c349b907-dc3a-4246-89e0-8d61e53f9aac)

Can you check?  @JKorf

**Comment by JKorf** [comment]
Your server time seems to be ahead of the Bybit server

**Comment by hcanak** [comment]
Sorry, you are right. 
The error is in .**V5Api.Account.GetAllAssetBalancesAsync(AccountType.Fund)**

_Error Message: Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'result.list[0].fundFee', line 1, position 63._

**Comment by JKorf** [comment]
Can you double check? The only property using fundFee is a leveraged token endpoint it seems

**Comment by hcanak** [comment]
> Can you double check? The only property using fundFee is a leveraged token endpoint it seems

I have issues about locating the error. The error is in GetLeverageTokensAsync endpoint.

**Comment by JKorf** [comment]
Right, this has been fixed in the latest version :)
