### ISSUE TITLE
Error in AccountUpdate_EventAsync at FundingFee event...

### ISSUE THREAD

**Issue by hcanak** [JKorf/Bybit.Net#203]
Hello,

In cross margin mode when a funding fee event triggered you get data in type of **BinanceFuturesStreamAccountUpdateData**
The issue is BinanceFuturesStreamAccountUpdateData.Positions does not have any member. See below ss.

![image](https://github.com/JKorf/Bybit.Net/assets/79494507/e24f61a0-7388-428c-823d-658a22cdd133)

I see this issue only in cross margin. In isolated margin, BinanceFuturesStreamAccountUpdateData.Positions has members as expected.

Thanks four your interest @JKorf

**Comment by JKorf** [comment]
Hi, looking at the documentation here: https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update it is documented that with funding fee updates in a crossed position the positions are not included. So this seems to be intended behavior

**Comment by hcanak** [comment]
I think that position info should be mandotory because you even do not know the symbol who has the funding fee...
