### ISSUE TITLE
WebSocket V5PrivateApi SubscribeToOrderUpdatesAsync missing enum

### ISSUE THREAD

**Issue by pgrimstrup** [JKorf/Bybit.Net#211]
Hi. I am using V5PrivateApi.SubscribeToOrderUpdatesAsync to listen for changes to orders, and noticed a log error message:

``
Cannot map enum value. EnumType: StopLossTakeProfitMode, Value: UNKNOWN, Known values: Full, Partial. If you think UNKNOWN should added please open an issue on the Github repo
``

I had my program listening for orders, while I placed an order _without_ any SL/TP using the ByBit website. However if a place an order _with_ a SL/TP, the error does not show.

Note that the order is still received via web socket, with the TpSlMode property set to null. The message is just a logged warning and doesn't impact the API in any way (low priority).

**Comment by pgrimstrup** [comment]
Started using Trailing Stops via the SetTradingStop() method and I am also receiving this error message;

``
Cannot map enum value. EnumType: StopOrderType, Value: TrailingProfit, Known values: TakeProfit, StopLoss, TrailingStop, Stop, PartialStopLoss, PartialTakeProfit, tpslOrder, OcoOrder, MmRateClose, BidirectionalTpslOrder. If you think TrailingProfit should added please open an issue on the Github repo
``
It appears to be pseudonym for TrailingStop, or just a typo from the API itself. It appears in the websocket feed for orders when a trailing stop is entered. As a result, the order is received as a Market Sell order as the StopOrderType field cannot be parsed.

**Comment by JKorf** [comment]
Added in latest version
