### ISSUE TITLE
Reduce for loop complexity from O(N^2) to O(N)

### ISSUE THREAD

**Issue by zhenkas** [JKorf/Bybit.Net#213]
In this section the response array recreated on every item in response array meaning complexity O(N^2)

Can reduce to O(N) by taking this line before the loop
https://github.com/JKorf/Bybit.Net/blob/1ef996ee167460027d5c746324e478aee7d9f821/ByBit.Net/Clients/V5/BybitRestClientApiTrading.cs#L146

**Comment by JKorf** [comment]
Makes sense, thanks for the PR
