### ISSUE TITLE
Error getting orderbook for options

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bybit.Net#216]
for example, this request get error
26.06.2024 11:18:46 52 Exception:Deserialize JsonReaderException: Could not convert to integer: 20514192230. Path 'result.u', line 1, position 349., Path: result.u, LineNumber: 1, LinePosition: 349
https://[api.bybit.com/v5/market/orderbook?category=option&baseCoin=BTC&expDate=26JUN24&symbol=BTC-28JUN24-62000-C](https://api.bybit.com/v5/market/orderbook?category=option&baseCoin=BTC&expDate=26JUN24&symbol=BTC-28JUN24-62000-C)

I think this field should be long, not int

**Comment by JKorf** [comment]
You're right, I'll fix it

**Comment by JKorf** [comment]
Fixed in latest version
