### ISSUE TITLE
Error getting positions

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bybit.Net#217]
15:46:32.91[9]DEBUG:[Bybit.API.Trace] [Req 27] Sending GET signed request to https://api.bybit.com/v5/position/list?category=linear&settleCoin=USDT with headers Accept=[application/json]

riskLimitValue should be nullable

15:46:33.15[46]ERROR:[Bybit.API.Warning] [Req 27] 200 - Error received in 223ms: [DeserializeError] Deserialize JsonSerializationException:
   Error converting value {null} to type 'System.Decimal'. Path 'result.list[0].riskLimitValue',
   line 1, position 218.
   
   {"retCode":0,"retMsg":"OK",
    "result":{"nextPageCursor":"BTCUSDT%2C1719388800005%2C0","category":"linear",
              "list":[
                {"symbol":"ETHUSDT","leverage":"","autoAddMargin":0,"avgPrice":"3825.41","liqPrice":"",
              
                 "riskLimitValue":"",
              
                 "takeProfit":"","positionValue":"76.5082","isReduceOnly":false,"tpslMode":"Full","riskId":0,"trailingStop":"0",
                 "unrealisedPnl":"-9.0838","markPrice":"3371.22","adlRankIndicator":2,"cumRealisedPnl":"-0.31461835","positionMM":"",
                 "createdTime":"1717701408942","positionIdx":0,"positionIM":"","seq":145728011071,"updatedTime":"1719388800013",
                 "side":"Buy","bustPrice":"","positionBalance":"","leverageSysUpdatedTime":"","curRealisedPnl":"-0.31461835",
                 "size":"0.02","positionStatus":"Normal","mmrSysUpdatedTime":"","stopLoss":"","tradeMode":0,"sessionAvgPrice":""},

              
                {"symbol":"BTCUSDT","leverage":"","autoAddMargin":0,"avgPrice":"71341.7","liqPrice":"",
                
                 "riskLimitValue":"",
                 
                 "takeProfit":"","positionValue":"71.3417","isReduceOnly":false,"tpslMode":"Full","riskId":0,"trailingStop":"0",
                 "unrealisedPnl":"-10.0011","markPrice":"61340.6","adlRankIndicator":2,"cumRealisedPnl":"-0.229903","positionMM":"",
                 "createdTime":"1717684845171","positionIdx":0,"positionIM":"","seq":197459260247,"updatedTime":"1719388800005",
                 "side":"Buy","bustPrice":"","positionBalance":"","leverageSysUpdatedTime":"","curRealisedPnl":"-0.229903",
                 "size":"0.001","positionStatus":"Normal","mmrSysUpdatedTime":"","stopLoss":"","tradeMode":0,"sessionAvgPrice":""}
                 
                       ]},"retExtInfo":{},"time":1719405993040}

**Comment by JKorf** [comment]
This was fixed in the latest version
