### ISSUE TITLE
How to get OHLC data

### ISSUE THREAD

**Issue by Knaackee** [JKorf/Bybit.Net#221]
First, thanks for the great work!

I am wondering how to get historical OHLC data for a given timeframe. 

I couldn't find relevant information in the documentation.

**Comment by JKorf** [comment]
Hi, OHLC data is referenced to as klines in the library. So you can use `client.V5Api.ExchangeData.GetKlinesAsync` to request it

**Comment by Knaackee** [comment]
Great, thank you!
