### ISSUE TITLE
BybitSpotPriceFilter properties missing

### ISSUE THREAD

**Issue by derzsky** [JKorf/Bybit.Net#223]
Version Bybit 3.9.0

**BybitSpotPriceFilter** has only **TickSize** property
```
    /// <summary>
    /// Price filter info
    /// </summary>
    public class BybitSpotPriceFilter
    {
        /// <summary>
        /// Tick size
        /// </summary>
        public decimal TickSize { get; set; }
    }
```

I believe it also should contain **MinPrice** and **MaxPrice**.

Reasons:
1. Bybit has these info in [their documentation](https://bybit-exchange.github.io/docs/v5/market/instrument)

![image](https://github.com/user-attachments/assets/b4efb6b3-5183-42b6-be62-23202fc61c2e)

![image](https://github.com/user-attachments/assets/5ec81cfa-59ec-4678-a2da-376ad84d5083)

2. These filters are needed to place correct orders on Bybit exchange.
3. Another exchange class **BinanceSymbolPriceFilter** contains all 3 properties:
```
    /// <summary>
    /// Price filter
    /// </summary>
    public class BinanceSymbolPriceFilter: BinanceSymbolFilter
    {
        /// <summary>
        /// The minimal price the order can be for
        /// </summary>
        public decimal MinPrice { get; set; }
        /// <summary>
        /// The max price the order can be for
        /// </summary>
        public decimal MaxPrice { get; set; }
        /// <summary>
        /// The tick size of the price. The price can not have more precision as this and can only be incremented in steps of this.
        /// </summary>
        public decimal TickSize { get; set; }
    }
```

**Comment by JKorf** [comment]
Hi, the response for the endpoint you mention is different for linear, spot and options. It show linear by default, which indeed has the min/max price properties. But if you switch to the Spot response structure you can see only the tickSize is available.

**Comment by derzsky** [comment]
Hello, thank you! Now I got it 😊
Resolving the issue...
