### ISSUE TITLE
Unable to use BybitSymbolOrderBook with Demo env

### ISSUE THREAD

**Issue by Amitabitbul** [JKorf/Bybit.Net#224]
Hi,

I'm trying to use BybitSymbolOrderBook, but when I'm switching to Demo env, it fails

The server returned status code '404' when status code '101' was expected,

When I'm switching back to Live, it works just fine, but then I'm not able to receive Account updates

Thanks!

**Comment by gmpatel** [comment]
Hi, how do you switch to demo env in Bybit.Net?

**Comment by JKorf** [comment]
The demo environment only supports the trading/account endpoints related to demo trading. For market data you'll need to use a client with the normal environment. 
Environment can be set in the client options like this
```
var client = new BybitSocketClient(x =>
{
    x.Environment = BybitEnvironment.DemoTrading;
});
```
