### ISSUE TITLE
GetCollateralInfoAsync startted to give error...

### ISSUE THREAD

**Issue by hcanak** [JKorf/Bybit.Net#226]
Hello @JKorf,

Below end point was working good until today.  Today it statted to give following error. Bybit might have changed th json format.

**V5Api.Account.GetCollateralInfoAsync()**

_Error Code: 
Error Message: Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'result.list[118].borrowUsageRate', line 1, position 37315._

**Comment by JKorf** [comment]
Hi, can confirm. It looks like there is now a null value returned which previously never happened. I'll fix it for next version

**Comment by hcanak** [comment]
Now, it is working properly. Null state of that variable seems to be volatile.

**Comment by JKorf** [comment]
Yeah probably. Either way last version supports null value
