### ISSUE TITLE
Wrong sort direction of Spot OrderBook entries

### ISSUE THREAD

**Issue by CitrusVento** [JKorf/Bybit.Net#23]
Example of ETHUSDT orderbook
  Wrong Top prices

   Ask quantity       Ask price | Bid price       Bid quantity
[        0.0056]        2630.25 | 2651.4         [0.06808       ]
[          2.04]        2631.34 | 2650           [0.05759       ]
[       7.74686]        2631.36 | 2648.61        [2.04          ]

**Comment by JKorf** [comment]
Thanks for the report, this has been fixed in the latest version
