### ISSUE TITLE
WebSocket V5PrivateApi SubscribeToOrderUpdatesAsync error

### ISSUE THREAD

**Issue by nighty79** [JKorf/Bybit.Net#231]
Hi. 
When I call V5PrivateApi.SubscribeToOrderUpdatesAsync, it returns "[Server Error] Authentication failed. Param Error".
Please explain what is wrong.
Thank you.

Follow is my code snippet.

            BybitSocketClient bybitSocket = new BybitSocketClient();
            bybitSocket.SetApiCredentials(new ApiCredentials("pdEWnPo...", "Af0xf07...LrjmX"));
            var result = await bybitSocket.V5PrivateApi.SubscribeToOrderUpdatesAsync(data =>
            {
                //do something
            });

Debug Log:
Bybit: Debug: [Sckt 2] created for wss://stream.bybit.com/v5/private
Bybit: Debug: [Sckt 2] adding new subscription with id 4, total subscriptions on connection: 1
Bybit: Debug: [Sckt 2] connecting
Bybit: Debug: [Sckt 2] connected to wss://stream.bybit.com/v5/private
Bybit: Debug: [Sckt 2] status changed from None to Connected
Bybit: Debug: [Sckt 2] starting processing tasks
Bybit: Debug: [Sckt 2] starting task checking for no data received for 00:00:30
Bybit: Debug: [Sckt 2] Attempting to authenticate
Bybit: Warning: [Sckt 2] authentication failed
Bybit: Debug: [Sckt 2] closing
Bybit: Debug: [Sckt 2] send loop finished
Bybit: Debug: [Sckt 2] receive loop finished
Bybit: Debug: [Sckt 2] processing tasks finished
Bybit: Debug: [Sckt 2] status changed from Connected to Closed
Bybit: Debug: [Sckt 2] closed
Bybit: Debug: [Sckt 2] disposing

**Comment by JKorf** [comment]
Hi, that should work. As the logging suggests it seems that your API credentials aren't correct.
