### ISSUE TITLE
V5Api.Trading.GetPositionsAsync TradeMode is wrong

### ISSUE THREAD

**Issue by kayahasa** [JKorf/Bybit.Net#232]
I am using GetPositionsAsync and although i am using Isolated in my Bybit account, the response of this enpoint is returning position.TradeMode as CROSS. 

There should be a mapping issue

**Comment by JKorf** [comment]
Hi, the field is only valid for Classic & UTA (inverse), so the field is not to be used for normal UTA trading. I'll add it in the description.
