### ISSUE TITLE
support orderbook grouping (dumpscale in api)

### ISSUE THREAD

**Issue by tanevanwifferen** [JKorf/Bybit.Net#235]
We can only fetch 200 levels deep at the smallest scale
Bybit has an undocumented websocket parameter to group orders in buckets of different size, namely dumpScale, which is specified as 

dumpScale = rounding by decimals 

so with a price delta of 0.0001 btc, dumpScale = is 4
with a price delta of 0.01 usd, dumpScale = is 2
with a price delta of 0.1 usd, dumpScale = is 1
with a price delta of 1 usd, dumpsScale is -1
with a price delta of 10 usd dumpScale = -2

**Comment by JKorf** [comment]
Hi I tried this but it doesn't seem to work for me. Can you share an example request?

**Comment by tanevanwifferen** [comment]
This is the websocket url. Not sure which version this is
wss://ws2.bybit.nl/spot/ws/quote/v2?_platform=2&timestamp=1726054361263

and this is the subscription request, taken from the website:
```
{
    event: "sub",
    limit: 40,
    params: {binary: false, dumpScale: -2},
    symbol: "BTCUSDT",
    topic: "mergedDepth"
}
```

**Comment by JKorf** [comment]
That doesn't seem to be an endpoint/connection from the public API
