### ISSUE TITLE
I am using "demo" account APIKey and SecretKey but it is not using demo environment

### ISSUE THREAD

**Issue by gmpatel** [JKorf/Bybit.Net#238]
How do I set SDK or package to use demo environment? Bybit.Net?

**Comment by JKorf** [comment]
You can set the environment in the client options, either in the constructor or during DI registration:
`options.Environment = Bybit.Net.BybitEnvironment.DemoTrading;`

**Comment by gmpatel** [comment]
Awesome, thanks for your response. Just figured it out from your repository... 👍
