### ISSUE TITLE
GetBalanceAync fails when balance is null

### ISSUE THREAD

**Issue by pgrimstrup** [JKorf/Bybit.Net#239]
Using Bybit.Net 3.14.1.0
I created a new Demo account and traded 48,983 USDT for BTC leaving 1,017 USDT, as this is my preferred starting balance for testing.

Calling the following code for a new coin that I have not performed any transactions with yet, such as POPCAT:
`Client.V5Api.Account.GetBalancesAsync(AccountType.Unified, "USDC,USDT," + coin);`

## Error Message
`[Req 28] 200 - Error received in 542ms: [DeserializeError] Deserialize JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path 'result.list[0].coin[2].walletBalance', line 1, position 1430. {"retCode":0,"retMsg":"OK","result":{"list":[{"totalEquity":"164744.68939582","accountIMRate":"0","totalMarginBalance":"51016.22042405","totalInitialMargin":"0","accountType":"UNIFIED","totalAvailableBalance":"51016.22042405","accountMMRate":"0","totalPerpUPL":"0","totalWalletBalance":"51016.22042405","accountLTV":"0","totalMaintenanceMargin":"0","coin":[{"availableToBorrow":"","bonus":"0","accruedInterest":"0","availableToWithdraw":"50000","totalOrderIM":"0","equity":"50000","totalPositionMM":"0","usdValue":"49999.1","unrealisedPnl":"0","collateralSwitch":true,"spotHedgingQty":"0","borrowAmount":"0.000000000000000000","totalPositionIM":"0","walletBalance":"50000","cumRealisedPnl":"0","locked":"0","marginCollateral":true,"coin":"USDC"},{"availableToBorrow":"","bonus":"0","accruedInterest":"0","availableToWithdraw":"1017.7218977","totalOrderIM":"0","equity":"1017.7218977","totalPositionMM":"0","usdValue":"1017.12042405","unrealisedPnl":"0","collateralSwitch":true,"spotHedgingQty":"0","borrowAmount":"0.000000000000000000","totalPositionIM":"0","walletBalance":"1017.7218977","cumRealisedPnl":"0","locked":"0","marginCollateral":true,"coin":"USDT"},{"availableToBorrow":"","bonus":"","accruedInterest":"","availableToWithdraw":"","totalOrderIM":"","equity":"","totalPositionMM":"","usdValue":"","unrealisedPnl":"","collateralSwitch":false,"spotHedgingQty":"0","borrowAmount":"","totalPositionIM":"","walletBalance":"","cumRealisedPnl":"","locked":"","marginCollateral":false,"coin":"POPCAT"}]}]},"retExtInfo":{},"time":1728425265393}``

## Problem
The problem is with the third coin: "walletBalance":""
BybitAssetBalance.WalletBalance property is not nullable. As a result, deserialization fails. 

## Possible Fixes
* Make WalletBalance nullable - this will be a breaking change
* Create a serializable _walletBalance property which is nullable, convert WalletBalance property to JsonIgnore with get/set accessors to get/set the _walletBalance property
* Are there any options for the JSON deserializer to convert an empty string to a 0 for non-nullable fields? Possibly use a Converter class?
Note that I haven't checked the source code for a fix, as the workaround will do for now.

## Workaround
Make a minimal purchase of the coin via Spot trading. This will set the balance to non-zero, allowing deserialization to complete successfully.

**Comment by JKorf** [comment]
Thanks for the detailed info, the property has been updated to be nullable in the latest version
