### ISSUE TITLE
"invalid parameter" in CreateInternalTransferAsync

### ISSUE THREAD

**Issue by CitrusVento** [JKorf/Bybit.Net#24]
https://bybit-exchange.github.io/docs/account_asset/#t-transfer_api
I think that request parameters should be included in request body

> `var transferResult = await bybitApiClient.GeneralApi.Transfer.CreateInternalTransferAsync(Guid.NewGuid().ToString(), "USDT", 10m,
                AccountType.Spot, AccountType.Contract);`

**Comment by JKorf** [comment]
The latest version should work for you!

**Comment by CitrusVento** [comment]
Fine! Thanks for your work.
Maybe you know when Bybit will add the ability to withdraw assets through the API?
