### ISSUE TITLE
SPOT: V5Api.Trading.PlaceOrderAsync sl/tp

### ISSUE THREAD

**Issue by codehunter13** [JKorf/Bybit.Net#242]
Hi, 
When using V5Api.Trading.PlaceOrderAsync with category SPOT and adding a stoploss or takeprofit i get the following error:
{[ServerError] 170003: An unknown parameter was sent.

![image](https://github.com/user-attachments/assets/350e2251-63d3-429a-b343-9c6a91342b87)

Regards,
Glenn

**Comment by JKorf** [comment]
Hi, you'll have to provide the `stopLossOrderType` and `takeProfitOrderType` parameters as well
