### ISSUE TITLE
Incorrect Error message on Stop Loss

### ISSUE THREAD

**Issue by andresdrb** [JKorf/Bybit.Net#244]
For some reason I get this error message "Failed Creating Stop Loss: Permission denied, please check your API key permissions." when trying to create a stop loss over a symbol that I don't have available balance anymore (instead of a "Not enough balance" message or something like that). I'm sure it is not an API permissions problem because is the same API key I use for everthing on ByBit. Thoughts @JKorf ?

**Comment by JKorf** [comment]
That's not something the library generates so it must be an issue on the server side I guess

**Comment by andresdrb** [comment]
Aparetly that method is not available for SPOT trading
