### ISSUE TITLE
SubscribeToOrderbookUpdatesAsync only works when depth is 1

### ISSUE THREAD

**Issue by q0v0p** [JKorf/Bybit.Net#245]
Does SubscribeToOrderbookUpdatesAsync only support a depth of 1?

![image](https://github.com/user-attachments/assets/3e9245fe-a96f-473a-a408-619a9bc2ea5b)

**Comment by JKorf** [comment]
Any reason you're looking in the source? What you're looking at there is an implementation of the a book ticker subscription for a shared interface. 
If you're looking to just subscribe to an order book stream you can use this:
```csharp
var subscriptionResult = bybitSocketClient.V5SpotApi.SubscribeToOrderbookUpdatesAsync("ETHUSDT", 50, update =>
{
    // Handle update
});
```
