### ISSUE TITLE
How to get Earn Wallet Balance?

### ISSUE THREAD

**Issue by hcanak** [JKorf/Bybit.Net#246]
Hello,

When i call _V5Api.Account.GetAllAssetBalancesAsync(AccountType.Investment)_  to get earn wallet balance, it gives following error. 
How can i get Earn Wallet Balance? Thanks for your great efford @JKorf .

![image](https://github.com/user-attachments/assets/02b34a22-72a3-444a-bed4-ca638f1c74ee)

**Comment by Kellytimmins** [comment]
Hello @hcanak 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BYB07638
Please see the link below to our dedicated support line:
[Bybit Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by REALDRAGNET** [comment]
"INVESTMENT" is not a valit account type, valid types are UNIFIED, CONTRACT and SPOT
Source:
https://bybit-exchange.github.io/docs/api-explorer/v5/account/wallet

**Comment by JKorf** [comment]
I didn't know the answer so I asked Bybit support but unfortunately it's not available via the API:
![image](https://github.com/user-attachments/assets/edebc663-5332-43f7-8b96-c1714535fc8a)
