### ISSUE TITLE
User Data Listen - Market Order - Status coming as 'Canceled' when buy something (sell is correct interestingly)

### ISSUE THREAD

**Issue by kayahasa** [JKorf/Bybit.Net#25]
Use Case: 
 bybitSocketClient.SpotStreams.SubscribeToAccountUpdatesAsync
 orderUpdate => {

}

Market Buy BTCUSDT -> orderUpdate.Status coming as Canceled. This one is NOT CORRECT! should be Filled.(even it is successful).
Market Sell BTCUSDT ->  orderUpdate.Status coming as Filled. This one is CORRECT.

**Comment by kayahasa** [comment]
This could help you...

2022/04/09 21:00:49:017 | Warning | Cannot map enum value. EnumType: Bybit.Net.Enums.OrderType, Value: MARKET_OF_QUOTE, Known values: LIMIT, MARKET, LIMIT_MAKER. If you think MARKET_OF_QUOTE should added please open an issue on the Github repo


This logs is coming from library code. I think you should add MARKET_OF_QUOTE value to the OrderType

**Comment by kayahasa** [comment]
If you want, you can directly map MARKET_OF_QUOTE types to MARKET.

**Comment by kayahasa** [comment]
I have resolved by updating 

OrderTypeSpotConverter as 

            new KeyValuePair<OrderType, string>(OrderType.Limit, "LIMIT"),
            new KeyValuePair<OrderType, string>(OrderType.Limit, "LIMIT_OF_QUOTE"),
            new KeyValuePair<OrderType, string>(OrderType.Limit, "LIMIT_OF_BASE"),
            new KeyValuePair<OrderType, string>(OrderType.Market, "MARKET"),
            new KeyValuePair<OrderType, string>(OrderType.Market, "MARKET_OF_QUOTE"),
            new KeyValuePair<OrderType, string>(OrderType.Market, "MARKET_OF_BASE"),
            new KeyValuePair<OrderType, string>(OrderType.LimitMaker, "LIMIT_MAKER")
            
            Could you please update it ?

**Comment by kayahasa** [comment]
For the Cancel issue, it is coming from Bybit Server and i think since it is Market order, we can assume Cancelled as Filled. 

But besides this issue, OrderType was also incorrect which can be resolved by applying my solution above.

**Comment by kayahasa** [comment]
I think it is something like order status. like Partially filled. But i dont know exact answer. I have mapped them to Limit and everything good for me

**Comment by JKorf** [comment]
I've added the mapping as you suggested in the latest version

**Comment by hasangetbaraka** [comment]
Thanks Jan, 

Best Regards...
