### ISSUE TITLE
Deserialize JsonSerializationException

### ISSUE THREAD

**Issue by danielhw2** [JKorf/Bybit.Net#26]
When I try to run the "SetLeverageAsync" I receive an Json Serialization Exception:

**Command line**:   var resultado = ClienteRest.InverseFuturesApi.Account.SetLeverageAsync("BTCUSDU22", 5, 5).Result;

**Result error message**: "Deserialize JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path 'result', line 1, position 70."

 ERRO=[22] Deserialize JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path 'result', line 1, position 70. data: {
  "ret_code": 0,
  "ret_msg": "OK",
  "ext_code": "",
  "ext_info": "",
  "result": null,
  "time_now": "1650487234.099507",
  "rate_limit_status": 74,
  "rate_limit_reset_ms": 1650487234098,
  "rate_limit": 75
}

I'm using the latest versions:
ByBit.Net 1.0.0
CryptoExchange.Net 5.1.7

**Comment by JKorf** [comment]
Hm weird, docs say it should be int. I've changed the result to `int?` so it should work either way

**Comment by danielhw2** [comment]
Thank you very much!
