### ISSUE TITLE
Soket - Spot Api  Subscribe All Symbols

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Bybit.Net#27]
Hello,
For the Spot API, can we listen to the price information of all symbols from the socket at the same time?
Thanks

**Comment by JKorf** [comment]
There is no way to do so offered by the API. That is, there is no single subscription which just pushes all tickers. You can just use `SubscribeToTickerUpdatesAsync` for each symbol though

**Comment by emin-karadag** [comment]
Thank you
