### ISSUE TITLE
SubscribeToBalanceUpdatesAsync -> BybitBalanceUpdate missing "Asset" property

### ISSUE THREAD

**Issue by danielhw2** [JKorf/Bybit.Net#28]
The class "BybitBalanceUpdate" in "namespace Bybit.Net.Objects.Models.Socket" is missing the "Asset" property, showing only the "WalletBalance" and "AvailableBalance". Version ByBit.Net 1.0.0 and CryptoExchange.Net 5.1.7

The log result from the handler:

{
  "Timestamp": "2022-04-21T21:10:05.3008907Z",
  "Topic": null,
  "OriginalData": "{\"topic\":\"wallet\",\"data\":[{\"user_id\":2052755,\"coin\":\"BTC\",\"available_balance\":\"0.00000000\",\"wallet_balance\":\"0.00000000\"}]}",
  "Data": [
    {
      "wallet_balance": 0.00000000,
      "available_balance": 0.00000000
    }
  ]
}

**Comment by JKorf** [comment]
I've added the Asset property in the latest version

**Comment by danielhw2** [comment]
Thank you very much!
