### ISSUE TITLE
Socket - Subscribe To All Ticker

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Bybit.Net#3]
Hello,
I want to listen to the price change of all symbols from the socket instantly. However, I couldn't find a method for this.
Do you have to listen separately for each symbol? (`SubscribeToTickerUpdatesAsync()`)
Thanks.

**Comment by JKorf** [comment]
Yes, as far as I'm aware the Bybit API doesn't support a subscription for all symbols. The docs are here:
https://bybit-exchange.github.io/docs/inverse/#t-introduction
If you see anything missing that is described there but not in the library let me know and I'll be happy to implement it

**Comment by emin-karadag** [comment]
Version: **0.0.1-beta2** bug fixed.
Thank you @JKorf :)
