### ISSUE TITLE
Missing position endpoint properties 

### ISSUE THREAD

**Issue by Amannda123** [JKorf/Bybit.Net#31]
Hey there, somehow PositionMode-property (position_idx in the json response) ... is missing in GetPositionsAsync() ... it is delivered with SubscribeToPositionUpdatesAsync() i would like to check if my symbosl are in the correct mode when setting up he bot. Could you add that? It should inherit from the base classes (by looking at your code)  but i have no clue why its not visible

**Comment by JKorf** [comment]
Hi, its available in the latest version. Initially it wasn't documented, so I didn't add it in. But seems like they've added it in the docs a little while ago, so I also added it in the library now

**Comment by Amannda123** [comment]
Nice ty <3

**Comment by Amannda123** [comment]
Nice ty <3
