### ISSUE TITLE
UsdPerpetualStreams has no SubscribeToAccountUpdatesAsync endpoint

### ISSUE THREAD

**Issue by kayahasa** [JKorf/Bybit.Net#32]
UsdPerpetualStreams has no SubscribeToAccountUpdatesAsync endpoint, could you please add that feature like in SpotStreams? 

Right now, if user changes his Leverage, we are not able to get that change via socket listening.

**Comment by JKorf** [comment]
I can only implement what is offered by the Bybit API, and looking at this 
https://bybit-exchange.github.io/docs/linear/#t-privatetopics
there is no endpoint for account updates
