### ISSUE TITLE
no authentication is provided for private endpoints

### ISSUE THREAD

**Issue by johnWinchester01** [JKorf/Bybit.Net#35]
set all the available api authentications in BybitSocketClientOptions still getting this error while trying to subscribe to user data such as bybitSocketClient.UsdPerpetualStreams.SubscribeToUserTradeUpdatesAsync

            var bybitSocketClient = new BybitSocketClient(new BybitSocketClientOptions()
            {

                AutoReconnect = true,
                UsdPerpetualStreamsOptions = new BybitSocketApiClientOptions()
                {
                    ApiCredentials = new ApiCredentials(textBox1.Text.Replace(" ", ""), textBox2.Text.Replace(" ", "")),
                },
                InversePerpetualStreamsOptions = new BybitSocketApiClientOptions()
                {
                    ApiCredentials = new ApiCredentials(textBox1.Text.Replace(" ", ""), textBox2.Text.Replace(" ", "")),
                },
                SpotStreamsOptions = new BybitSocketApiClientOptions()
                {
                    ApiCredentials = new ApiCredentials(textBox1.Text.Replace(" ", ""), textBox2.Text.Replace(" ", "")),
                },
                InverseFuturesStreamsOptions=new BybitSocketApiClientOptions()
                {
                    ApiCredentials = new ApiCredentials(textBox1.Text.Replace(" ", ""), textBox2.Text.Replace(" ", "")),
                },
                SocketResponseTimeout = TimeSpan.FromSeconds(1),
                SocketSubscriptionsCombineTarget = 2,
                OutputOriginalData = true,
                LogLevel = Microsoft.Extensions.Logging.LogLevel.Trace,
                ApiCredentials = new ApiCredentials(textBox1.Text.Replace(" ", ""), textBox2.Text.Replace(" ", "")),
            });
and
            var t = await bybitSocketClient.UsdPerpetualStreams.SubscribeToTradeUpdatesAsync(Crypto.Name, TradesHandler);
returns "Authentication failed: No credentials provided for private endpoint"

**Comment by JKorf** [comment]
I can't reproduce it, the code you posted seems to work for me. Are you sure you're using the same socket client to subscribe as you set the options on? This gives no issues for me:

````csharp

var bybitSocketClient = new BybitSocketClient(new BybitSocketClientOptions()
{
    AutoReconnect = true,
    UsdPerpetualStreamsOptions = new BybitSocketApiClientOptions()
    {
        ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials("KEY", "SECRET")
    },
    InversePerpetualStreamsOptions = new BybitSocketApiClientOptions()
    {
        ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials("KEY", "SECRET")
    },
    SpotStreamsOptions = new BybitSocketApiClientOptions()
    {
        ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials("KEY", "SECRET")
    },
    InverseFuturesStreamsOptions = new BybitSocketApiClientOptions()
    {
       ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials("KEY", "SECRET")
    },
    SocketResponseTimeout = TimeSpan.FromSeconds(10),
    SocketSubscriptionsCombineTarget = 2,
    OutputOriginalData = true,
    LogLevel = Microsoft.Extensions.Logging.LogLevel.Trace,
    ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials("KEY", "SECRET")
});

var t = await bybitSocketClient.UsdPerpetualStreams.SubscribeToUserTradeUpdatesAsync(data =>
{
    Console.WriteLine("data");
});

````


Note that 1 second ResponseTimout might be a bit short

**Comment by johnWinchester01** [comment]
Yes i can confirm that the sameclient is being used also even this reproduces the same error for me:
ApiCredentials apiC = new ApiCredentials(textBox1.Text.Trim(), textBox2.Text.Trim());
            bybitSocketClient.ClientOptions.OutputOriginalData = true;
            bybitSocketClient.ClientOptions.ApiCredentials = apiC;

            t = await bybitSocketClient.UsdPerpetualStreams.SubscribeToUserTradeUpdatesAsync(OrderHandler);
            if (t.Success)
            {
                Log("[INF]", "Trades monitor started");
            }
            else
            {
                Log("[ERR]", "Socket Error:" + t.Error.Message);
                
            }
            
is there anything Im missing?permissions of the api key/seceret maybe?

**Comment by JKorf** [comment]
The issue here is that the client options should be set on construction of the client. Setting it after doesn't work correctly. 
Setting it like this should work:
````
var bybitSocketClient = new BybitSocketClient(new Bybit.Net.Objects.BybitSocketClientOptions
{
    LogLevel = LogLevel.Trace,
    ApiCredentials = ApiCredentials(textBox1.Text.Trim(), textBox2.Text.Trim())
});
````
