### ISSUE TITLE
UsdPerpetualApi.Account.GetPositionAsync always returns 2 positions

### ISSUE THREAD

**Issue by johnWinchester01** [JKorf/Bybit.Net#36]
using UsdPerpetualApi.Account.GetPositionAsync always returns 2 positions even tho I have closed all the positions from both api and the website 

2022/05/18 04:37:52:191 | Information | Bybit      | [14] Creating request for https://api.bytick.com/private/linear/order/cancel-all
2022/05/18 04:37:52:193 | Trace | Bybit      | [14] Sending POST signed request to https://api.bytick.com/private/linear/order/cancel-all with request body 'api_key=oItbqDLH4CW8nyYeER&recv_window=10000&symbol=GMTUSDT&timestamp=1652832472193&sign=C6677AD6FFB0BCF6A870357629F162BA933E02904B8217471E5D4B7C1C590FE5' with headers Accept=[application/json], x-referer=[JKorf]
2022/05/18 04:37:52:822 | Debug | Bybit      | [14] Response received in 459ms: {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":null,"time_now":"1652832474.491359","rate_limit_status":90,"rate_limit_reset_ms":1652832474489,"rate_limit":100}
2022/05/18 04:37:52:837 | Information | Bybit      | [17] Creating request for https://api.bytick.com/private/linear/position/list
2022/05/18 04:37:52:838 | Trace | Bybit      | [17] Sending GET signed request to https://api.bytick.com/private/linear/position/list?api_key=oItbqDLH4CW8nyYeER&recv_window=10000&symbol=GMTUSDT&timestamp=1652832472838&sign=D49208FB45924205109BF071A867C3F787CD325A42EBF53E7BB25065EEBB2C79 with headers Accept=[application/json], x-referer=[JKorf]
2022/05/18 04:37:53:158 | Debug | Bybit      | [17] Response received in 317ms: {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":[{"user_id":24638417,"symbol":"GMTUSDT","side":"Buy","size":0,"position_value":0,"entry_price":0,"liq_price":0,"bust_price":0,"leverage":10,"auto_add_margin":0,"is_isolated":true,"position_margin":0,"occ_closing_fee":0,"realised_pnl":0,"cum_realised_pnl":-1.3423082,"free_qty":0,"tp_sl_mode":"Full","unrealised_pnl":0,"deleverage_indicator":0,"risk_id":1,"stop_loss":0,"take_profit":0,"trailing_stop":0,"position_idx":1,"mode":"BothSide"},{"user_id":24638417,"symbol":"GMTUSDT","side":"Sell","size":0,"position_value":0,"entry_price":0,"liq_price":0,"bust_price":0,"leverage":10,"auto_add_margin":0,"is_isolated":true,"position_margin":0,"occ_closing_fee":0,"realised_pnl":0,"cum_realised_pnl":-0.23675725,"free_qty":0,"tp_sl_mode":"Full","unrealised_pnl":0,"deleverage_indicator":0,"risk_id":1,"stop_loss":0,"take_profit":0,"trailing_stop":0,"position_idx":2,"mode":"BothSide"}],"time_now":"1652832474.978014","rate_limit_status":119,"rate_limit_reset_ms":1652832474974,"rate_limit":120}

**Comment by JKorf** [comment]
I suggest asking this to the Bybit team, I don't know the expected behavior and can't fix it on the library side

**Comment by klausbyskov** [comment]
I think this is the expected behavior. Bybit allows you to be long and short at the same time. Therefore the api returns a position for buy side (long) and a position for sell side (short). Even if those positions have a size of 0.
