### ISSUE TITLE
Condition Order Trigger Price not visible

### ISSUE THREAD

**Issue by fatihalsan** [JKorf/Bybit.Net#38]
TriggerPrice, StopLossPrice missing in BybitConditionalOrder class can you check that?

<img width="706" alt="Screen Shot 2022-06-12 at 15 01 42" src="https://user-images.githubusercontent.com/32260998/173232155-c456f2f9-12c8-4292-9fe5-a429f6792772.png">

<img width="554" alt="Screen Shot 2022-06-12 at 15 00 09" src="https://user-images.githubusercontent.com/32260998/173232157-707b59e5-d42a-4766-b089-f0bcdd751ba8.png">

**Comment by JKorf** [comment]
Should be fixed in the latest version

**Comment by klausbyskov** [comment]
> Should be fixed in the latest version

The fix is incomplete, because `IBybitClient.UsdPerpetualApi.Trading.GetOpenConditionalOrdersRealTimeAsync` returns a `WebCallResult<IEnumerable<BybitConditionalOrder>>` instead of returning `...<BybitConditionalOrderUsd>>` where the fix was introduced.

**Comment by dante1989** [comment]
> > Should be fixed in the latest version
> 
> The fix is incomplete, because `IBybitClient.UsdPerpetualApi.Trading.GetOpenConditionalOrdersRealTimeAsync` returns a `WebCallResult<IEnumerable<BybitConditionalOrder>>` instead of returning `...<BybitConditionalOrderUsd>>` where the fix was introduced.

i have the same Problem: IBybitClient.UsdPerpetualApi.Trading.GetOpenConditionalOrdersRealTimeAsync returns a WebCallResult<IEnumerable<BybitConditionalOrder>> instead of returning ...<BybitConditionalOrderUsd>>
