### ISSUE TITLE
Spot Api Klines Error 2

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Bybit.Net#45]
Hello,
I'm running the GetKlinesAsync() method using the Bybit Spot API. However, as far as I can see, the 'CloseTime' field among the incoming data is always null.
Thank you.

```
var klineResult = await client.SpotApi.ExchangeData.GetKlinesAsync("1SOLUSDT", Bybit.Net.Enums.KlineInterval.OneMonth, ct: stoppingToken);
if (klineResult.Success && klineResult.Data.Any())
{

}
```

**Comment by kulikov-dev** [comment]
Looks like it's not a Bybit.net issue. Check this query from any REST checker and the close time will = 0.
So,  I bet it's a bybit issue, maybe because of this explanation from API docs ("If startTime and endTime are not specified, only the latest candles will be sent").

**Comment by kulikov-dev** [comment]
@JKorf I guess, it should be closed.
