### ISSUE TITLE
SubscribeToStopOrderUpdatesAsync fails when PartialStopLoss or PartialTakeProfit are used

### ISSUE THREAD

**Issue by jserranog74** [JKorf/Bybit.Net#46]
When I use partial mode position in UsdPerpetualStreams, this subscribe method will be called with those Stop order types and this error is received:

2022/07/06 07:40:08:714 | Warning | Cannot map enum value. EnumType: Bybit.Net.Enums.StopOrderType, Value: PartialStopLoss, Known values: TakeProfit, StopLoss, TrailingStop, Stop. If you think PartialStopLoss should added please open an issue on the Github repo
2022/07/06 07:40:08:716 | Error | Bybit      | Deserialize JsonSerializationException: Error setting value to 'StopOrderType' on 'Bybit.Net.Objects.Models.Socket.BybitUsdPerpetualStopOrderUpdate'. data: [

I think both types should be added to StopOrderType enumerator and properly conversion to class StopOrderTypeConverter.

**Comment by JKorf** [comment]
The PartialStopLoss type has been added, let me know if you have any other issues
