### ISSUE TITLE
UsdPerpetualApi, InverseFuturesApi and InversePerpetualApi invalid request !

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Bybit.Net#48]
Hello,
When I make any request to places other than the Spot API (Example: Bringing balance information), I get an error with the code 10002.

**Bybit.Net Version:** v1.0.6
**Error Code:**           10002
**Error Message:**      invalid request, please check your timestamp and recv_window param. req_timestamp: 1657479201370 server_timestamp: 1657479200284 recv_window: 5000

Sample Code:

 `var res = await client.InverseFuturesApi.Account.GetBalancesAsync();`

**Comment by JKorf** [comment]
Are you using .Net framework? Then have a look here: #42
