### ISSUE TITLE
403 error 

### ISSUE THREAD

**Issue by johnWinchester01** [JKorf/Bybit.Net#49]
hello with this new update i encounter this error while trying to fetch the currencies endpoints
<html><head><title>Access Denied</title></head><body><h1>Access Denied</h1>You don't have permission to access "/v2/public/symbols" on this server.<br/>0.ece83217.1658441122.750f9789</body></html>

**Comment by JKorf** [comment]
I can't reproduce this, and it sounds like it's not an issue of this library (the endpoint is public but you don't have permission?)
