### ISSUE TITLE
Socket Data Null Fields

### ISSUE THREAD

**Issue by emin-karadag** [JKorf/Bybit.Net#5]
Hi,
While reading data from the socket, a lot of data comes as 'null'.
Also, many socket functions for both Spot and Futures don't seem to work properly.
Thanks.
![Ekran Alıntısı](https://user-images.githubusercontent.com/7556164/148659831-83de9b61-ca98-4aba-bdeb-85b56846294a.PNG)

**Comment by JKorf** [comment]
I've fixed an issue in exponential value parsing in the latest version, that should help.
If you have streams that don't seem to work well please let me know which subscription it is with which parameters.

**Comment by emin-karadag** [comment]
Hello,
Thank you for the instant price listening feature of more than one symbol at the same time.
Also, a lot of null fields seem to be fixed.

However, there is a problem. When I run the code below; BTCUSDT price information coming in and correct.
ETHUSDT price information is coming and right.
EOSUSDT price information is coming and right.

**Then EOSUSDT price information comes again and it is WRONG. Many fields are null.
After that, instant price listening is no longer possible.**


```
var futuresSymbols = await _bybitService.GetAllFuturesSymbolsAsync(stoppingToken).ConfigureAwait(false);
if (futuresSymbols.Any())
{
    var symbols = futuresSymbols.Where(p => p.Name.EndsWith("USDT")).Select(p => p.Name);
    var socketClient = new BybitSocketClient();
    await socketClient.UsdPerpetualStreams.SubscribeToTickerUpdatesAsync(symbols, data =>
    {
        var aa = data;
    }, stoppingToken).ConfigureAwait(false);
}
```

**Comment by JKorf** [comment]
Hi, so I checked this out, and found what the `issue` is. Initially the server sends a snapshot for each symbol with all info. After that it will only send updates for properties which have changed. If a property hasn't changed it will therefor remain `null` and should be ignored. Hope this clears things up
