### ISSUE TITLE
Headge mode support

### ISSUE THREAD

**Issue by MichalGrzegorzak** [JKorf/Bybit.Net#51]
Bybit allows headging mode on future contracts. Any plans to support it?

**Comment by dante1989** [comment]
> Bybit allows headging mode on future contracts. Any plans to support it?

var client = new BybitClient();  
var result = await client.UsdPerpetualApi.Account.SetPositionModeAsync(/* parameters */);  
Task<WebCallResult> SetPositionModeAsync(string symbol, bool hedgeMode, long? receiveWindow = default, CancellationToken ct = default);

var client = new BybitClient();  
var result = await client.InverseFuturesApi.Account.SetPositionModeAsync(/* parameters */);  
Task<WebCallResult> SetPositionModeAsync(string symbol, bool hedgeMode, long? receiveWindow = default, CancellationToken ct = default);

Bybit now support Hedge Mode for UsdPerpetual and InverseFuture but not for Inverse InversePerpetual
