### ISSUE TITLE
Future Api Klines Error

### ISSUE THREAD

**Issue by dante1989** [JKorf/Bybit.Net#53]
Dim clientBybit = New BybitClient 'API Bybit Exchange
        clientBybit.SetApiCredentials(New ApiCredentials(API_Bybit1, Secret_Bybit1))
Dim m1d_BybitFuture As WebCallResult(Of IEnumerable(Of BybitKline))
Dim Fromtime as Date="1/1/2020"
 m1d_BybitFuture = Await clientBybit.UsdPerpetualApi.ExchangeData.GetKlinesAsync("ETHUSDT", KlineIntervalBybit.OneHour , fromtime, 24 )

I was expecting i got:
m1d_BybitFuture.Data(0).OpenTime="1/1/2020"
m1d_BybitFuture.Data(m1d_BybitFuture.Data.Count - 1).OpenTime="1/1/2020 11:00:00 PM"

But I got this wrong answer: 
m1d_BybitFuture.Data(0).OpenTime="10/21/2020 9:00:00 AM"
m1d_BybitFuture.Data(m1d_BybitFuture.Data.Count - 1).OpenTime="10/22/2020 8:00:00 AM"

Spot is ok, true answer but UsdPerpetualApi and InversePerpetualApi get wrong answer
Please help me to fix this. Thank you

**Comment by dante1989** [comment]
i just found out that this error only appears for the period before 1/1/2021. And after January 1, 2021, the results are completely normal


> Dim clientBybit = New BybitClient 'API Bybit Exchange clientBybit.SetApiCredentials(New ApiCredentials(API_Bybit1, Secret_Bybit1)) Dim m1d_BybitFuture As WebCallResult(Of IEnumerable(Of BybitKline)) Dim Fromtime as Date="1/1/2020" m1d_BybitFuture = Await clientBybit.UsdPerpetualApi.ExchangeData.GetKlinesAsync("ETHUSDT", KlineIntervalBybit.OneHour , fromtime, 24 )
> 
> I was expecting i got: m1d_BybitFuture.Data(0).OpenTime="1/1/2020" m1d_BybitFuture.Data(m1d_BybitFuture.Data.Count - 1).OpenTime="1/1/2020 11:00:00 PM"
> 
> But I got this wrong answer: m1d_BybitFuture.Data(0).OpenTime="10/21/2020 9:00:00 AM" m1d_BybitFuture.Data(m1d_BybitFuture.Data.Count - 1).OpenTime="10/22/2020 8:00:00 AM"
> 
> Spot is ok, true answer but UsdPerpetualApi and InversePerpetualApi get wrong answer Please help me to fix this. Thank you

i just found out that this error only appears for the period before 1/1/2021. And after January 1, 2021, the results are completely normal

**Comment by JKorf** [comment]
Well that seems to be an issue in their data. I'll close that as it seems to be fixed
