### ISSUE TITLE
bybit.net does not sync with bybit servers correctly

### ISSUE THREAD

**Issue by johnWinchester01** [JKorf/Bybit.Net#56]
Hi, after getting no response on the issue i opened a while ago (still open) i did a little more digging and i noticed that the time on the events i get via websocket is about 8 minutes( more or less) ago.at first i thought it's a timezone issue and changed my time zone to UTC among a few othe timezones and synced them accuratly but the error still exists.
[Here's a photo showing my problem](Https://ibb.co/BgwFPN2)

**Comment by JKorf** [comment]
Sorry, can you elaborate on what the issue in the photo is? Can you confirm you are processing update quick enough?

**Comment by johnWinchester01** [comment]
> Sorry, can you elaborate on what the issue in the photo is? Can you confirm you are processing update quick enough?
the time on my windows as shown is 18:22 but the trades i get from websocket happened at 18:22. yes i can confirm there is no issue with my internet speed and im not even proccessing anything it's just a straight up Debug.WriteLine. no lock statement or anyting.

**Comment by JKorf** [comment]
I don't really see how this is 8 minutes delay. It seems to be fairly close to your windows time? Events listed are from 18:21:45 while you current time is 18:22:xx
What timestamps fields are you printing there?

**Comment by johnWinchester01** [comment]
im sorry this issue should've been closed a while ago there was a memory leak in my application which i fixed later on. feel free to close the issue.and thanks for the awesome job on this lib.
