### ISSUE TITLE
GetPositions Inverse Perpetual contracts going wrong

### ISSUE THREAD

**Issue by wilcot1989** [JKorf/Bybit.Net#6]
The api call refers to the futures api call. Fix is: 
![image](https://user-images.githubusercontent.com/56579130/149834873-cbff285c-6cc0-4fbe-92c7-310816b74dd3.png)
To this: 
![image](https://user-images.githubusercontent.com/56579130/149834917-3bf80117-95a8-48a5-b098-b8ecee034136.png)
In the BybitClientInversePerpetualApiTrading.cs class.

Thanks :-)

**Comment by JKorf** [comment]
Thanks, this has been fixed by your PR. I found another endpoint not being correct, also fixed that.
I've pushed version beta2 which should be available shortly.

**Comment by wilcot1989** [comment]
Thanks! When i found something more, i let you know.
