### ISSUE TITLE
Bybit Copy Trading Permission Denied

### ISSUE THREAD

**Issue by CryptoTradee** [JKorf/Bybit.Net#62]
Hi,

Thanks so much for creating all these exchange integrations! Was very happy when I saw you have done a Bybit one too.

However 2 comments:
* I'm trying to get the balance of the copy trading wallet and Bybit is returning "permission denied" error. I've tried with an api key that has full access
* Also, could you enable an option to be able to set the timeout so getting your wallet balances doesn't need you to have your time server synced.

Thanks

**Comment by JKorf** [comment]
Hi, the Copy Trading API is only available for principal traders, so that might be the issue you're seeing.
I'm not sure I understand your second question/request? There is the receiveWindow parameter which you could set larger if that's what you're looking for.

**Comment by CryptoTradee** [comment]
Ok thanks
