### ISSUE TITLE
derivatives ?

### ISSUE THREAD

**Issue by Kei-OHKAWA** [JKorf/Bybit.Net#63]
Do you support **derivatives**?

Are there any plans to support **derivatives** in the future?

**Comment by dante1989** [comment]
> 

You can check derivative APIs here:
https://jkorf.github.io/Bybit.Net/ClientInfo/UsdPerpetualApi/IBybitClientUsdPerpetualApi.html
https://jkorf.github.io/Bybit.Net/ClientInfo/InversePerpetualApi/IBybitClientInversePerpetualApi.html

**Comment by Kei-OHKAWA** [comment]
Thank you. understood.
