### ISSUE TITLE
PlaceOrderAsync() is very slow

### ISSUE THREAD

**Issue by ThaiCat** [JKorf/Bybit.Net#65]
Bybit.Net.Clients.UsdPerpetualApi.PlaceOrderAsync() always takes more than 5 seconds to finish.
I set receiveWindow: 60000 as a workaround, but I think there something wrong with the method. All other methods in Bybit.Net.Clients.UsdPerpetualApi I tested so far take less time to complete combined, even when run sequentially.

**Comment by JKorf** [comment]
Check out #42

**Comment by ThaiCat** [comment]
Thanks, it helped.
