### ISSUE TITLE
SpotApi wrong timestamp

### ISSUE THREAD

**Issue by opiman** [JKorf/Bybit.Net#74]
Hello.
I dont understand whats wrong but if I call SpotApiV3.ExchangeData.GetKlinesAsync with start and end time so returned another dates (my timezone +7)

request: 
![image](https://user-images.githubusercontent.com/36917950/195860695-eb2e77e6-1ab3-4c46-a444-cb695e39bccc.png)

response:
![image](https://user-images.githubusercontent.com/36917950/195860719-18a89cd2-9c42-4acf-9c7f-819304cba341.png)

**Comment by ThaiCat** [comment]
try using UTC time

**Comment by opiman** [comment]
its already utc kind

**Comment by kulikov-dev** [comment]
@opiman It looks like an issue with v3 API, which not uses begin/end time parameters.
If you send the raw request via postman like:
https://api-testnet.bybit.com/spot/v3/public/quote/kline?symbol=BTCUSDT&interval=15m&startTime=1665709200000&endTime=1665712800000

Where we have one hour diff and 15 minutes interval - it returns around 1000 values, which not correct.
API v1 works as expected.

**Comment by JKorf** [comment]
I've checked with the API team, it's an issue in the API where startTime and endTime are being ignored. They're going to look into it

**Comment by opiman** [comment]
ok got it. thanks
