### ISSUE TITLE
Error in new place order with SL/TP

### ISSUE THREAD

**Issue by hamedmaleki1366** [JKorf/Bybit.Net#78]
Hello,

I have problem in adding new place order with stoploss and takeprofit. 

this is my code : 
`
var ordrId = Guid.NewGuid().ToString();

                var newPosition = await bybitClient.UsdPerpetualApi.Trading.PlaceOrderAsync(
                    signal.Coin,
                    signal.Direction == "short" ? OrderSide.Sell : OrderSide.Buy,
                    OrderType.Limit, qty ,
                    TimeInForce.ImmediateOrCancel,
                    true,true, entryPrice,clientOrderId: ordrId,
                   takeProfitPrice: target,
                   stopLossPrice: signal.StopLoss, TriggerType.MarkPrice, TriggerType.MarkPrice);
`

After this code executed , I got this error
`130125: current position is zero, cannot fix reduce-only order qty`

I just need new position with SL/TP . 

What's the problem?

Thanks in advance.

**Comment by kulikov-dev** [comment]
@hamedmaleki1366 Hello. Please pay attention to the "reduce_only" parameter. You don't have an open position but set up a reduce-only parameter as true, which causes a problem.

**Comment by kulikov-dev** [comment]
@hamedmaleki1366 if it helped, please mark the answer as accepted and close the issue. Tnx.

**Comment by JKorf** [comment]
Assuming this is solved
