### ISSUE TITLE
Include CoinBalanceInAccount in Account Asset V3

### ISSUE THREAD

**Issue by CryptoTradee** [JKorf/Bybit.Net#81]
[CoinBalanceInAccount.zip](https://github.com/JKorf/Bybit.Net/files/10036844/CoinBalanceInAccount.zip)

Hi,

I was looking for a way to get the account balance for investment accounts. I see the api CoinBalanceInAccount works for that in Account Asset V3. This is new as I've looked for this very often.

I went ahead and implemented it within your code within the attached zip. Please include in main.

https://bybit-exchange.github.io/docs/account_asset/v3/#t-queryaccountcoinbalance

**Comment by JKorf** [comment]
Hi, I appreciate any contribution to the project, but please create a pull request for it instead of sending zip files. As you can imagine I"m not to keen on opening zip files from strangers ;)

**Comment by CryptoTradee** [comment]
BybitClientGeneralApiTransfer.cs
/// <inheritdoc />
        public async Task<WebCallResult<CoinBalanceQuery>> CoinBalanceInAccount(AccountType accountType, string asset, long? receiveWindow = null, CancellationToken ct = default)
        {

            string queryUrl = "asset/v3/private/transfer/account-coin/balance/query";

            var parameters = new Dictionary<string, object>()
            {
                { "accountType", EnumConverter.GetString(accountType) },
                { "coin", asset }
            };
            
            parameters.AddOptionalParameter("recvWindow", receiveWindow?.ToString(CultureInfo.InvariantCulture) ?? _baseClient.ClientOptions.ReceiveWindow.TotalMilliseconds.ToString(CultureInfo.InvariantCulture));

            return await _baseClient.SendRequestAsync<CoinBalanceQuery>(_baseClient.GetUrl(queryUrl), HttpMethod.Get, ct, parameters, true).ConfigureAwait(false);

        }

**Comment by CryptoTradee** [comment]
CoinBalanceQuery

using Bybit.Net.Enums;
using Newtonsoft.Json;

namespace Bybit.Net.Objects.Models
{
    public class CoinBalanceQuery
    {

        [JsonProperty("accountType")]
        public AccountType AccountType { get; set; }

        [JsonProperty("bizType")]
        public int BizType { get; set; }

        [JsonProperty("accountId")]
        public int AccountId { get; set; }

        [JsonProperty("memberId")]
        public int UserId { get; set; }

        [JsonProperty("balance")]
        public QueryBalance Balance { get; set; }
        


    }

    public class QueryBalance
    {

        /// <summary>
        /// The asset
        /// </summary>
        [JsonProperty("coin")]
        public string? Asset { get; set; }
        
        /// <summary>
        /// Wallet balance
        /// </summary>
        [JsonProperty("walletBalance")]
        public decimal WalletBalance { get; set; }
        
        [JsonProperty("transferBalance")]
        public decimal transferBalance { get; set; }

        [JsonProperty("bonus")]
        public string BonusAmount { get; set; }

    }
}

**Comment by CryptoTradee** [comment]
IBybitClientGeneralApiTransfer.cs

        /// <summary>
        /// Coin balance for an account type including Earn
        /// <para><a href="https://bybit-exchange.github.io/docs/account_asset/v3/#t-queryaccountcoinbalance" /></para>
        /// </summary>
        /// <param name="accountType"></param>
        /// <param name="asset">Coin symbol</param>
        /// <param name="receiveWindow">The receive window for which this request is active. When the request takes longer than this to complete the server will reject the request</param>
        /// <param name="ct">Cancellation token</param>
        /// <returns></returns>
        Task<WebCallResult<CoinBalanceQuery>> CoinBalanceInAccount(AccountType accountType, string asset, long? receiveWindow = null, CancellationToken ct = default);

**Comment by CryptoTradee** [comment]
Sorry, already had cloned your original repo. Hope the above helps. Just the 3 files.

**Comment by kulikov-dev** [comment]
@CryptoTradee  Done, thank you.

**Comment by CryptoTradee** [comment]
Thanks @kulikov-dev . 
@JKorf  - be included soon?

**Comment by kulikov-dev** [comment]
@JKorf Issue can be closed.

**Comment by JKorf** [comment]
Has been added under GeneralApi.Transfer.GetAssetBalanceAsync in the latest release
