### ISSUE TITLE
SubscribeToKlinesUpdatesAsync does not work...

### ISSUE THREAD

**Issue by hcanak** [JKorf/Bybit.Net#84]
hi,

I wanted to subscribe to all kline update for all symbols but it gives the following error:  Am i missing something?

![image](https://user-images.githubusercontent.com/79494507/202767757-8cab67be-9cc5-4ea1-9d7a-71853a8bb669.png)

**Comment by hcanak** [comment]
@kulikov-dev
The symbol parameter of SubscribeToKlineUpdatesAsync is NOT ienumerable, it is string. How can i combine all symbols correctly?

**Comment by kulikov-dev** [comment]
@hcanak There are two signatures of this method. The second one contains Ienumerable param of symbols:
![image](https://user-images.githubusercontent.com/40471760/204152558-12a68470-8080-48f2-a95b-1b32d11ee7a7.png)

**Comment by hcanak** [comment]
@kulikov-dev  Thank you:)
