### ISSUE TITLE
SpotApiV3.Trading.PlaceBorrowOrderAsync error!!

### ISSUE THREAD

**Issue by jacksoliman** [JKorf/Bybit.Net#89]
I receive an error when I try to place a borrow order in the Bybit spot market.

the code:

Client.bybitClient.SpotApiV3.Trading.PlaceBorrowOrderAsync(coinCurrency, size, receiveWindow: 20000);

Client = a Bybit client;
coinCurrency = string "USDT";
size = decimal 300;

The order is not successful and it returns the following error:

"Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Int64' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'result', line 1, position 95.

**Comment by kulikov-dev** [comment]
@jacksoliman  Thank you. Bugfix was created.

**Comment by jacksoliman** [comment]
Thank you for the quick response. I updated the 2 files but now it returns another error.

"Deserialize JsonReaderException: Unexpected character encountered while parsing value: {. Path 'result', line 1, position 92., Path: result, LineNumber: 1, LinePosition: 92"

**Comment by kulikov-dev** [comment]
@jacksoliman Sorry for the long responce, tried to reproduce and figure out the issue. Check the next commit in the fix please, it should help.

**Comment by jacksoliman** [comment]
Works perfect. You're an amazing person and a phenomenal programmer. Thank you.

**Comment by kulikov-dev** [comment]
You're welcome

**Comment by kulikov-dev** [comment]
@JKorf  Issue can be closed.
