### ISSUE TITLE
IBybitSocketClientUsdPerpetualStreams.SubscribeToKlineUpdatesAsync hadler event data do not contain interval

### ISSUE THREAD

**Issue by Netstep** [JKorf/Bybit.Net#92]
for example, I want to subscribe to ETH one minute klines
```
            var client = new BybitSocketClient();
            await client.UsdPerpetualStreams.SubscribeToKlineUpdatesAsync(new[]{"ETHUSDT"}, KlineInterval.OneMinute, OnKlineData);

        private static async void OnKlineData(DataEvent<IEnumerable<BybitKlineUpdate>> dataEvt)
        {
            if (dataEvt.Topic == null) return;
            var symbol = dataEvt.Topic;

            foreach (var data in dataEvt.Data)
            {
                if (!data.Confirm) continue;
                Console.WriteLine(symbol + " " + data.CloseTime.ToString("G"));
            }
        } 
```
I get value "ETHUSDT" in the dataEvt.Topic, but according to docs, I should get string like "candle.1.ETHUSDT", which contains the interval and symbol, I subscribed for, but in BybitKlineUpdate.Topic there is only symbol and no info about the interval, which is important.

**Comment by kulikov-dev** [comment]
@JKorf As I see, you did this on some purpose. Could you explain it please? I can agree with @Netstep that this information is important, so we can add new field in response or return not splitted topic.

``` C#
  handler(data.As(desResult.Data, topic.Split('.').Last()));
```

**Comment by JKorf** [comment]
I agree that in this case, where there is additional information in the subscription topic, it should be set to the full event topic. Generally the prefix of the topic isn't interesting as you should already know what the topic of the data is and you're probably only interested in what symbol the data is for. But in this case it should at least include the interval yes. I'll update it

**Comment by JKorf** [comment]
Has been fixed in the latest version
